// Generated by scripts/gen-meera-voice.ts — do not edit by hand.
export const VOICE_MANIFEST: Partial<Record<'hi' | 'en' | 'mr', Record<string, { file: string; seconds: number }>>> = {
  "hi": {
    "intro": {
      "file": "meera-voice/hi/intro.wav",
      "seconds": 8.533
    },
    "setup-0": {
      "file": "meera-voice/hi/setup-0.wav",
      "seconds": 7.339
    },
    "setup-2": {
      "file": "meera-voice/hi/setup-2.wav",
      "seconds": 10.24
    },
    "setup-5": {
      "file": "meera-voice/hi/setup-5.wav",
      "seconds": 6.4
    },
    "paste-2": {
      "file": "meera-voice/hi/paste-2.wav",
      "seconds": 11.093
    },
    "paste-5": {
      "file": "meera-voice/hi/paste-5.wav",
      "seconds": 3.84
    },
    "send-2": {
      "file": "meera-voice/hi/send-2.wav",
      "seconds": 6.4
    },
    "money-0": {
      "file": "meera-voice/hi/money-0.wav",
      "seconds": 11.435
    },
    "money-3": {
      "file": "meera-voice/hi/money-3.wav",
      "seconds": 8.363
    },
    "find-3": {
      "file": "meera-voice/hi/find-3.wav",
      "seconds": 7.851
    },
    "find-7": {
      "file": "meera-voice/hi/find-7.wav",
      "seconds": 6.571
    },
    "outro": {
      "file": "meera-voice/hi/outro.wav",
      "seconds": 16.128
    }
  },
  "en": {
    "intro": {
      "file": "meera-voice/en/intro.wav",
      "seconds": 6.656
    },
    "setup-0": {
      "file": "meera-voice/en/setup-0.wav",
      "seconds": 8.875
    },
    "setup-2": {
      "file": "meera-voice/en/setup-2.wav",
      "seconds": 12.971
    },
    "setup-5": {
      "file": "meera-voice/en/setup-5.wav",
      "seconds": 7.851
    },
    "paste-2": {
      "file": "meera-voice/en/paste-2.wav",
      "seconds": 12.373
    },
    "paste-5": {
      "file": "meera-voice/en/paste-5.wav",
      "seconds": 5.376
    },
    "send-2": {
      "file": "meera-voice/en/send-2.wav",
      "seconds": 6.912
    },
    "money-0": {
      "file": "meera-voice/en/money-0.wav",
      "seconds": 12.544
    },
    "money-3": {
      "file": "meera-voice/en/money-3.wav",
      "seconds": 8.789
    },
    "find-3": {
      "file": "meera-voice/en/find-3.wav",
      "seconds": 9.216
    },
    "find-7": {
      "file": "meera-voice/en/find-7.wav",
      "seconds": 6.741
    },
    "outro": {
      "file": "meera-voice/en/outro.wav",
      "seconds": 17.323
    }
  },
  "mr": {
    "intro": {
      "file": "meera-voice/mr/intro.wav",
      "seconds": 8.96
    },
    "setup-0": {
      "file": "meera-voice/mr/setup-0.wav",
      "seconds": 9.301
    },
    "setup-2": {
      "file": "meera-voice/mr/setup-2.wav",
      "seconds": 11.349
    },
    "setup-5": {
      "file": "meera-voice/mr/setup-5.wav",
      "seconds": 8.533
    },
    "paste-2": {
      "file": "meera-voice/mr/paste-2.wav",
      "seconds": 12.885
    },
    "paste-5": {
      "file": "meera-voice/mr/paste-5.wav",
      "seconds": 6.229
    },
    "send-2": {
      "file": "meera-voice/mr/send-2.wav",
      "seconds": 6.229
    },
    "money-0": {
      "file": "meera-voice/mr/money-0.wav",
      "seconds": 10.411
    },
    "money-3": {
      "file": "meera-voice/mr/money-3.wav",
      "seconds": 7.339
    },
    "find-3": {
      "file": "meera-voice/mr/find-3.wav",
      "seconds": 8.704
    },
    "find-7": {
      "file": "meera-voice/mr/find-7.wav",
      "seconds": 6.485
    },
    "outro": {
      "file": "meera-voice/mr/outro.wav",
      "seconds": 17.579
    }
  }
};
