package com.influora.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.influora.domain.entity.MediaMetric;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

/**
 * Phase 2 Data Pipeline: Unit tests for MediaMetricsRepository.
 *
 * <p>NOTE: MediaMetricsRepository is a pure Spring Data JPA interface with ONLY derived-query
 * methods (findFirstBy*, findBy*OrderBy*) — there are NO custom @Query implementations. All methods
 * are auto-generated by Spring Data's query derivation mechanism from their method names.
 *
 * <p>There is no custom implementation code to unit-test in isolation without a real database. This
 * test file confirms the method signatures are correct and callable via Mockito; actual query
 * correctness (e.g., that ORDER BY time DESC returns the newest row first) is validated in
 * integration tests with @DataJpaTest or the full integration test suite running against a real
 * MySQL database.
 *
 * <p>Unit-testing auto-generated Spring Data query derivation would be testing Spring Data's own
 * query-generation logic, not our code — which is why this test is deliberately minimal (signature
 * verification only).
 *
 * <p>Coverage per KAVYA_QA_TEST_PLAN.md §2.3 + SHARED_CONTEXT.md Phase 2 entry.
 */
@ExtendWith(MockitoExtension.class)
class MediaMetricsRepositoryTest {

    private static final String MEDIA_ID = "instagram_media_12345";
    private static final String CREATOR_ID = "01HWXYZCREATOR000000001";
    private static final String PLATFORM_INSTAGRAM = "INSTAGRAM";

    @Mock private MediaMetricsRepository repository;

    @Test
    @DisplayName("findFirstByMediaIdOrderByTimeDesc: derived query for most recent media snapshot")
    void testFindFirstByMediaIdOrderByTimeDesc() {
        // Spring Data derived query — no custom JPQL. Confirms method signature is callable.

        Instant now = Instant.now();
        MediaMetric metric =
                createMetric("01MM1", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, now, 5000L);

        when(repository.findFirstByMediaIdOrderByTimeDesc(MEDIA_ID))
                .thenReturn(Optional.of(metric));

        Optional<MediaMetric> result = repository.findFirstByMediaIdOrderByTimeDesc(MEDIA_ID);

        assertTrue(result.isPresent());
        assertEquals(MEDIA_ID, result.get().getMediaId());
        verify(repository).findFirstByMediaIdOrderByTimeDesc(MEDIA_ID);
    }

    @Test
    @DisplayName("findByCreatorProfileIdOrderByTimeDesc: derived query with Pageable")
    void testFindByCreatorProfileIdOrderByTimeDesc() {
        // Spring Data derived query for recent per-post metrics, newest first.

        Instant now = Instant.now();
        MediaMetric metric =
                createMetric("01MM1", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, now, 5000L);

        Pageable pageable = PageRequest.of(0, 25);
        when(repository.findByCreatorProfileIdOrderByTimeDesc(CREATOR_ID, pageable))
                .thenReturn(List.of(metric));

        List<MediaMetric> result =
                repository.findByCreatorProfileIdOrderByTimeDesc(CREATOR_ID, pageable);

        assertEquals(1, result.size());
        verify(repository).findByCreatorProfileIdOrderByTimeDesc(CREATOR_ID, pageable);
    }

    @Test
    @DisplayName("findByCreatorProfileIdAndPlatformOrderByTimeDesc: derived query scoped by platform")
    void testFindByCreatorProfileIdAndPlatformOrderByTimeDesc() {
        // Spring Data derived query with platform scoping.

        Instant now = Instant.now();
        MediaMetric metric =
                createMetric("01MM1", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, now, 5000L);

        Pageable pageable = PageRequest.of(0, 25);
        when(repository.findByCreatorProfileIdAndPlatformOrderByTimeDesc(
                        CREATOR_ID, PLATFORM_INSTAGRAM, pageable))
                .thenReturn(List.of(metric));

        List<MediaMetric> result =
                repository.findByCreatorProfileIdAndPlatformOrderByTimeDesc(
                        CREATOR_ID, PLATFORM_INSTAGRAM, pageable);

        assertEquals(1, result.size());
        verify(repository)
                .findByCreatorProfileIdAndPlatformOrderByTimeDesc(
                        CREATOR_ID, PLATFORM_INSTAGRAM, pageable);
    }

    @Test
    @DisplayName("findByCreatorProfileIdAndTimeBetweenOrderByTimeAsc: derived query for time-range")
    void testFindByCreatorProfileIdAndTimeBetweenOrderByTimeAsc() {
        // Spring Data derived query with time-range filtering.

        Instant now = Instant.now();
        Instant from = now.minus(7, ChronoUnit.DAYS);

        MediaMetric metric =
                createMetric("01MM1", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, now, 5000L);

        when(repository.findByCreatorProfileIdAndTimeBetweenOrderByTimeAsc(CREATOR_ID, from, now))
                .thenReturn(List.of(metric));

        List<MediaMetric> result =
                repository.findByCreatorProfileIdAndTimeBetweenOrderByTimeAsc(CREATOR_ID, from, now);

        assertEquals(1, result.size());
        verify(repository).findByCreatorProfileIdAndTimeBetweenOrderByTimeAsc(CREATOR_ID, from, now);
    }

    @Test
    @DisplayName("findByMediaIdOrderByTimeAsc: derived query for all snapshots of one media item")
    void testFindByMediaIdOrderByTimeAsc() {
        // Spring Data derived query for per-post history, oldest first.

        Instant now = Instant.now();
        Instant older = now.minus(1, ChronoUnit.HOURS);

        MediaMetric metric1 =
                createMetric("01MM1", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, older, 5000L);
        MediaMetric metric2 =
                createMetric("01MM2", MEDIA_ID, CREATOR_ID, PLATFORM_INSTAGRAM, now, 6000L);

        when(repository.findByMediaIdOrderByTimeAsc(MEDIA_ID))
                .thenReturn(List.of(metric1, metric2));

        List<MediaMetric> result = repository.findByMediaIdOrderByTimeAsc(MEDIA_ID);

        assertEquals(2, result.size());
        verify(repository).findByMediaIdOrderByTimeAsc(MEDIA_ID);
    }

    /**
     * Helper to create a test MediaMetric instance — uses builder pattern matching the entity's
     * actual API.
     */
    private MediaMetric createMetric(
            String id,
            String mediaId,
            String creatorId,
            String platform,
            Instant time,
            long impressions) {
        return MediaMetric.builder()
                .id(id)
                .time(time)
                .mediaId(mediaId)
                .creatorProfileId(creatorId)
                .platform(platform)
                .mediaType("IMAGE")
                .impressions(impressions)
                .dataSource("META_API")
                .fetchedAt(time)
                .build();
    }
}
