R="/sessions/rcw-01wmb7a52u3r92s2wv26nrs2/mnt/New Influora"
T="$R/_to_delete/md-sweep-2026-07-24"
mkdir -p "$T"
mkdir -p "$T/.cursor/agents"
mkdir -p "$T/.pytest_cache"
mkdir -p "$T/BLUEPRINT"
mkdir -p "$T/claude-skills"
mkdir -p "$T/claude-skills/aframe-webxr"
mkdir -p "$T/claude-skills/animated-component-libraries"
mkdir -p "$T/claude-skills/animejs"
mkdir -p "$T/claude-skills/babylonjs-engine"
mkdir -p "$T/claude-skills/barba-js"
mkdir -p "$T/claude-skills/blender-web-pipeline"
mkdir -p "$T/claude-skills/code-reviewer"
mkdir -p "$T/claude-skills/commit-crafter"
mkdir -p "$T/claude-skills/council"
mkdir -p "$T/claude-skills/gsap-scrolltrigger"
mkdir -p "$T/claude-skills/impeccable"
mkdir -p "$T/claude-skills/lean-output"
mkdir -p "$T/claude-skills/lightweight-3d-effects"
mkdir -p "$T/claude-skills/locomotive-scroll"
mkdir -p "$T/claude-skills/lottie-animations"
mkdir -p "$T/claude-skills/modern-web-design"
mkdir -p "$T/claude-skills/motion-framer"
mkdir -p "$T/claude-skills/pixijs-2d"
mkdir -p "$T/claude-skills/playcanvas-engine"
mkdir -p "$T/claude-skills/react-spring-physics"
mkdir -p "$T/claude-skills/react-three-fiber"
mkdir -p "$T/claude-skills/rive-interactive"
mkdir -p "$T/claude-skills/scroll-reveal-libraries"
mkdir -p "$T/claude-skills/spline-interactive"
mkdir -p "$T/claude-skills/substance-3d-texturing"
mkdir -p "$T/claude-skills/terse-mode"
mkdir -p "$T/claude-skills/threejs-webgl"
mkdir -p "$T/claude-skills/web3d-integration-patterns"
mkdir -p "$T/claude-skills/writing-style"
mkdir -p "$T/deploy/hostinger"
mkdir -p "$T/docs"
mkdir -p "$T/docs/docs"
mkdir -p "$T/docs/features"
mkdir -p "$T/docs/reports"
mkdir -p "$T/docs/security"
mkdir -p "$T/influora-ai/.pytest_cache"
mkdir -p "$T/influora-ai/evals"
mkdir -p "$T/node_modules/acorn"
mkdir -p "$T/node_modules/acorn-import-attributes"
mkdir -p "$T/node_modules/acorn-jsx"
mkdir -p "$T/node_modules/agent-base"
mkdir -p "$T/node_modules/ajv"
mkdir -p "$T/node_modules/ansi-colors"
mkdir -p "$T/node_modules/ansi-regex"
mkdir -p "$T/node_modules/ansi-styles"
mkdir -p "$T/node_modules/aria-hidden"
mkdir -p "$T/node_modules/aria-query"
mkdir -p "$T/node_modules/assertion-error"
mkdir -p "$T/node_modules/ast-types"
mkdir -p "$T/node_modules/asynckit"
mkdir -p "$T/node_modules/atomically"
mkdir -p "$T/node_modules/autoprefixer"
mkdir -p "$T/node_modules/axe-core"
mkdir -p "$T/node_modules/b4a"
mkdir -p "$T/node_modules/balanced-match"
mkdir -p "$T/node_modules/bare-events"
mkdir -p "$T/node_modules/bare-fs"
mkdir -p "$T/node_modules/bare-os"
mkdir -p "$T/node_modules/bare-path"
mkdir -p "$T/node_modules/bare-stream"
mv -n "$R/DEPENDENCIES.md" "$T/DEPENDENCIES.md"
mv -n "$R/DEPLOY-UTHO-VPS.md" "$T/DEPLOY-UTHO-VPS.md"
mv -n "$R/DEPLOY.md" "$T/DEPLOY.md"
mv -n "$R/EXTERNAL-APIS.md" "$T/EXTERNAL-APIS.md"
mv -n "$R/GEO-TECHNICAL-AUDIT.md" "$T/GEO-TECHNICAL-AUDIT.md"
mv -n "$R/README.md" "$T/README.md"
mv -n "$R/RUN-LOCAL.md" "$T/RUN-LOCAL.md"
mv -n "$R/SHARED_CONTEXT.md" "$T/SHARED_CONTEXT.md"
mv -n "$R/.pytest_cache/README.md" "$T/.pytest_cache/README.md"
mv -n "$R/BLUEPRINT/00-MASTER-BLUEPRINT.md" "$T/BLUEPRINT/00-MASTER-BLUEPRINT.md"
mv -n "$R/BLUEPRINT/06-DEPLOYMENT-AND-API-KEYS.md" "$T/BLUEPRINT/06-DEPLOYMENT-AND-API-KEYS.md"
mv -n "$R/BLUEPRINT/10-RUN-ON-SERVER-UTHO.md" "$T/BLUEPRINT/10-RUN-ON-SERVER-UTHO.md"
mv -n "$R/claude-skills/INSTALLED-2026-07-13.md" "$T/claude-skills/INSTALLED-2026-07-13.md"
mv -n "$R/claude-skills/README.md" "$T/claude-skills/README.md"
mv -n "$R/docs/ai.md" "$T/docs/ai.md"
mv -n "$R/docs/api.md" "$T/docs/api.md"
mv -n "$R/docs/architecture.md" "$T/docs/architecture.md"
mv -n "$R/docs/authentication.md" "$T/docs/authentication.md"
mv -n "$R/docs/authorization.md" "$T/docs/authorization.md"
mv -n "$R/docs/backend.md" "$T/docs/backend.md"
mv -n "$R/docs/BUSINESS-BLUEPRINT.md" "$T/docs/BUSINESS-BLUEPRINT.md"
mv -n "$R/docs/coding-guidelines.md" "$T/docs/coding-guidelines.md"
mv -n "$R/docs/database.md" "$T/docs/database.md"
mv -n "$R/docs/deployment.md" "$T/docs/deployment.md"
mv -n "$R/docs/developer-onboarding.md" "$T/docs/developer-onboarding.md"
mv -n "$R/docs/environment.md" "$T/docs/environment.md"
mv -n "$R/docs/external-services.md" "$T/docs/external-services.md"
mv -n "$R/docs/folder-structure.md" "$T/docs/folder-structure.md"
mv -n "$R/docs/frontend.md" "$T/docs/frontend.md"
mv -n "$R/docs/known-limitations.md" "$T/docs/known-limitations.md"
mv -n "$R/docs/performance.md" "$T/docs/performance.md"
mv -n "$R/docs/project-overview.md" "$T/docs/project-overview.md"
mv -n "$R/docs/README.md" "$T/docs/README.md"
mv -n "$R/docs/security.md" "$T/docs/security.md"
mv -n "$R/.cursor/agents/ananya.md" "$T/.cursor/agents/ananya.md"
mv -n "$R/.cursor/agents/arjun.md" "$T/.cursor/agents/arjun.md"
mv -n "$R/.cursor/agents/kabir.md" "$T/.cursor/agents/kabir.md"
mv -n "$R/.cursor/agents/kavya.md" "$T/.cursor/agents/kavya.md"
mv -n "$R/.cursor/agents/meera.md" "$T/.cursor/agents/meera.md"
mv -n "$R/.cursor/agents/priya.md" "$T/.cursor/agents/priya.md"
mv -n "$R/.cursor/agents/rohan.md" "$T/.cursor/agents/rohan.md"
mv -n "$R/.cursor/agents/swapnil.md" "$T/.cursor/agents/swapnil.md"
mv -n "$R/.cursor/agents/vikram.md" "$T/.cursor/agents/vikram.md"
mv -n "$R/claude-skills/aframe-webxr/SKILL.md" "$T/claude-skills/aframe-webxr/SKILL.md"
mv -n "$R/claude-skills/animated-component-libraries/SKILL.md" "$T/claude-skills/animated-component-libraries/SKILL.md"
mv -n "$R/claude-skills/animejs/SKILL.md" "$T/claude-skills/animejs/SKILL.md"
mv -n "$R/claude-skills/babylonjs-engine/SKILL.md" "$T/claude-skills/babylonjs-engine/SKILL.md"
mv -n "$R/claude-skills/barba-js/SKILL.md" "$T/claude-skills/barba-js/SKILL.md"
mv -n "$R/claude-skills/blender-web-pipeline/SKILL.md" "$T/claude-skills/blender-web-pipeline/SKILL.md"
mv -n "$R/claude-skills/code-reviewer/SKILL.md" "$T/claude-skills/code-reviewer/SKILL.md"
mv -n "$R/claude-skills/commit-crafter/SKILL.md" "$T/claude-skills/commit-crafter/SKILL.md"
mv -n "$R/claude-skills/council/SKILL.md" "$T/claude-skills/council/SKILL.md"
mv -n "$R/claude-skills/gsap-scrolltrigger/SKILL.md" "$T/claude-skills/gsap-scrolltrigger/SKILL.md"
mv -n "$R/claude-skills/impeccable/SKILL.md" "$T/claude-skills/impeccable/SKILL.md"
mv -n "$R/claude-skills/lean-output/SKILL.md" "$T/claude-skills/lean-output/SKILL.md"
mv -n "$R/claude-skills/lightweight-3d-effects/SKILL.md" "$T/claude-skills/lightweight-3d-effects/SKILL.md"
mv -n "$R/claude-skills/locomotive-scroll/SKILL.md" "$T/claude-skills/locomotive-scroll/SKILL.md"
mv -n "$R/claude-skills/lottie-animations/SKILL.md" "$T/claude-skills/lottie-animations/SKILL.md"
mv -n "$R/claude-skills/modern-web-design/SKILL.md" "$T/claude-skills/modern-web-design/SKILL.md"
mv -n "$R/claude-skills/motion-framer/SKILL.md" "$T/claude-skills/motion-framer/SKILL.md"
mv -n "$R/claude-skills/pixijs-2d/SKILL.md" "$T/claude-skills/pixijs-2d/SKILL.md"
mv -n "$R/claude-skills/playcanvas-engine/SKILL.md" "$T/claude-skills/playcanvas-engine/SKILL.md"
mv -n "$R/claude-skills/react-spring-physics/SKILL.md" "$T/claude-skills/react-spring-physics/SKILL.md"
mv -n "$R/claude-skills/react-three-fiber/SKILL.md" "$T/claude-skills/react-three-fiber/SKILL.md"
mv -n "$R/claude-skills/rive-interactive/SKILL.md" "$T/claude-skills/rive-interactive/SKILL.md"
mv -n "$R/claude-skills/scroll-reveal-libraries/SKILL.md" "$T/claude-skills/scroll-reveal-libraries/SKILL.md"
mv -n "$R/claude-skills/spline-interactive/SKILL.md" "$T/claude-skills/spline-interactive/SKILL.md"
mv -n "$R/claude-skills/substance-3d-texturing/SKILL.md" "$T/claude-skills/substance-3d-texturing/SKILL.md"
mv -n "$R/claude-skills/terse-mode/SKILL.md" "$T/claude-skills/terse-mode/SKILL.md"
mv -n "$R/claude-skills/threejs-webgl/SKILL.md" "$T/claude-skills/threejs-webgl/SKILL.md"
mv -n "$R/claude-skills/web3d-integration-patterns/SKILL.md" "$T/claude-skills/web3d-integration-patterns/SKILL.md"
mv -n "$R/claude-skills/writing-style/SKILL.md" "$T/claude-skills/writing-style/SKILL.md"
mv -n "$R/deploy/hostinger/ACCESS-GUIDE.md" "$T/deploy/hostinger/ACCESS-GUIDE.md"
mv -n "$R/deploy/hostinger/README.md" "$T/deploy/hostinger/README.md"
mv -n "$R/docs/docs/ai.md" "$T/docs/docs/ai.md"
mv -n "$R/docs/docs/api.md" "$T/docs/docs/api.md"
mv -n "$R/docs/docs/architecture.md" "$T/docs/docs/architecture.md"
mv -n "$R/docs/docs/authentication.md" "$T/docs/docs/authentication.md"
mv -n "$R/docs/docs/authorization.md" "$T/docs/docs/authorization.md"
mv -n "$R/docs/docs/backend.md" "$T/docs/docs/backend.md"
mv -n "$R/docs/docs/coding-guidelines.md" "$T/docs/docs/coding-guidelines.md"
mv -n "$R/docs/docs/database.md" "$T/docs/docs/database.md"
mv -n "$R/docs/docs/deployment.md" "$T/docs/docs/deployment.md"
mv -n "$R/docs/docs/developer-onboarding.md" "$T/docs/docs/developer-onboarding.md"
mv -n "$R/docs/docs/environment.md" "$T/docs/docs/environment.md"
mv -n "$R/docs/docs/external-services.md" "$T/docs/docs/external-services.md"
mv -n "$R/docs/docs/folder-structure.md" "$T/docs/docs/folder-structure.md"
mv -n "$R/docs/docs/frontend.md" "$T/docs/docs/frontend.md"
mv -n "$R/docs/docs/known-limitations.md" "$T/docs/docs/known-limitations.md"
mv -n "$R/docs/docs/performance.md" "$T/docs/docs/performance.md"
mv -n "$R/docs/docs/project-overview.md" "$T/docs/docs/project-overview.md"
mv -n "$R/docs/docs/README.md" "$T/docs/docs/README.md"
mv -n "$R/docs/docs/security.md" "$T/docs/docs/security.md"
mv -n "$R/docs/features/admin-dashboard.md" "$T/docs/features/admin-dashboard.md"
mv -n "$R/docs/features/affiliate-coupons.md" "$T/docs/features/affiliate-coupons.md"
mv -n "$R/docs/features/analytics.md" "$T/docs/features/analytics.md"
mv -n "$R/docs/features/authentication.md" "$T/docs/features/authentication.md"
mv -n "$R/docs/features/billing-subscriptions.md" "$T/docs/features/billing-subscriptions.md"
mv -n "$R/docs/features/brand-dashboard.md" "$T/docs/features/brand-dashboard.md"
mv -n "$R/docs/features/campaign-funding-flow.md" "$T/docs/features/campaign-funding-flow.md"
mv -n "$R/docs/features/campaigns.md" "$T/docs/features/campaigns.md"
mv -n "$R/docs/features/collaborations-deals.md" "$T/docs/features/collaborations-deals.md"
mv -n "$R/docs/features/contracts.md" "$T/docs/features/contracts.md"
mv -n "$R/docs/features/conversion-tracking.md" "$T/docs/features/conversion-tracking.md"
mv -n "$R/docs/features/creator-dashboard.md" "$T/docs/features/creator-dashboard.md"
mv -n "$R/docs/features/creator-profiles-portfolio.md" "$T/docs/features/creator-profiles-portfolio.md"
mv -n "$R/docs/features/deliverables.md" "$T/docs/features/deliverables.md"
mv -n "$R/docs/features/disputes.md" "$T/docs/features/disputes.md"
mv -n "$R/docs/features/escrow.md" "$T/docs/features/escrow.md"
mv -n "$R/docs/features/invoicing-gst.md" "$T/docs/features/invoicing-gst.md"
mv -n "$R/docs/features/marketplace-discovery.md" "$T/docs/features/marketplace-discovery.md"
mv -n "$R/docs/features/meera-ai.md" "$T/docs/features/meera-ai.md"
mv -n "$R/docs/features/meta-integration.md" "$T/docs/features/meta-integration.md"
mv -n "$R/docs/features/notifications.md" "$T/docs/features/notifications.md"
mv -n "$R/docs/features/payouts.md" "$T/docs/features/payouts.md"
mv -n "$R/docs/features/platform-fees.md" "$T/docs/features/platform-fees.md"
mv -n "$R/docs/features/reports-exports.md" "$T/docs/features/reports-exports.md"
mv -n "$R/docs/features/reviews.md" "$T/docs/features/reviews.md"
mv -n "$R/docs/features/shopify-integration.md" "$T/docs/features/shopify-integration.md"
mv -n "$R/docs/features/support-tickets.md" "$T/docs/features/support-tickets.md"
mv -n "$R/docs/features/trendspark.md" "$T/docs/features/trendspark.md"
mv -n "$R/docs/features/uploads-storage.md" "$T/docs/features/uploads-storage.md"
mv -n "$R/docs/features/wallet.md" "$T/docs/features/wallet.md"
mv -n "$R/docs/features/woocommerce-integration.md" "$T/docs/features/woocommerce-integration.md"
mv -n "$R/docs/features/workspaces-members.md" "$T/docs/features/workspaces-members.md"
mv -n "$R/docs/reports/MASTER-BUSINESS-PLAN.md" "$T/docs/reports/MASTER-BUSINESS-PLAN.md"
mv -n "$R/docs/reports/PRIYA-FIX-PATCHES-2026-07-15.md" "$T/docs/reports/PRIYA-FIX-PATCHES-2026-07-15.md"
mv -n "$R/docs/security/meera-onbehalf-auth-security-design.md" "$T/docs/security/meera-onbehalf-auth-security-design.md"
mv -n "$R/docs/security/trendspark-recovery-tagger-audit.md" "$T/docs/security/trendspark-recovery-tagger-audit.md"
mv -n "$R/influora-ai/.pytest_cache/README.md" "$T/influora-ai/.pytest_cache/README.md"
mv -n "$R/influora-ai/evals/README.md" "$T/influora-ai/evals/README.md"
mv -n "$R/node_modules/acorn/CHANGELOG.md" "$T/node_modules/acorn/CHANGELOG.md"
mv -n "$R/node_modules/acorn/README.md" "$T/node_modules/acorn/README.md"
mv -n "$R/node_modules/acorn-import-attributes/README.md" "$T/node_modules/acorn-import-attributes/README.md"
mv -n "$R/node_modules/acorn-jsx/README.md" "$T/node_modules/acorn-jsx/README.md"
mv -n "$R/node_modules/agent-base/README.md" "$T/node_modules/agent-base/README.md"
mv -n "$R/node_modules/ajv/README.md" "$T/node_modules/ajv/README.md"
mv -n "$R/node_modules/ansi-colors/README.md" "$T/node_modules/ansi-colors/README.md"
mv -n "$R/node_modules/ansi-regex/readme.md" "$T/node_modules/ansi-regex/readme.md"
mv -n "$R/node_modules/ansi-styles/readme.md" "$T/node_modules/ansi-styles/readme.md"
mv -n "$R/node_modules/aria-hidden/README.md" "$T/node_modules/aria-hidden/README.md"
mv -n "$R/node_modules/aria-query/CHANGELOG.md" "$T/node_modules/aria-query/CHANGELOG.md"
mv -n "$R/node_modules/aria-query/README.md" "$T/node_modules/aria-query/README.md"
mv -n "$R/node_modules/assertion-error/README.md" "$T/node_modules/assertion-error/README.md"
mv -n "$R/node_modules/ast-types/README.md" "$T/node_modules/ast-types/README.md"
mv -n "$R/node_modules/asynckit/README.md" "$T/node_modules/asynckit/README.md"
mv -n "$R/node_modules/atomically/readme.md" "$T/node_modules/atomically/readme.md"
mv -n "$R/node_modules/autoprefixer/README.md" "$T/node_modules/autoprefixer/README.md"
mv -n "$R/node_modules/axe-core/README.md" "$T/node_modules/axe-core/README.md"
mv -n "$R/node_modules/b4a/README.md" "$T/node_modules/b4a/README.md"
mv -n "$R/node_modules/balanced-match/LICENSE.md" "$T/node_modules/balanced-match/LICENSE.md"
mv -n "$R/node_modules/balanced-match/README.md" "$T/node_modules/balanced-match/README.md"
mv -n "$R/node_modules/bare-events/README.md" "$T/node_modules/bare-events/README.md"
mv -n "$R/node_modules/bare-fs/README.md" "$T/node_modules/bare-fs/README.md"
mv -n "$R/node_modules/bare-os/README.md" "$T/node_modules/bare-os/README.md"
mv -n "$R/node_modules/bare-path/README.md" "$T/node_modules/bare-path/README.md"
mv -n "$R/node_modules/bare-stream/README.md" "$T/node_modules/bare-stream/README.md"
echo DONE
