// Generated by scripts/gen-campaign-voice.ts — do not edit by hand.
export const CREATOR_VOICE: Record<string, { file: string; seconds: number }> = {
  "hook": {
    "file": "creator-voice/hook.wav",
    "seconds": 10.837
  },
  "browse": {
    "file": "creator-voice/browse.wav",
    "seconds": 11.264
  },
  "apply": {
    "file": "creator-voice/apply.wav",
    "seconds": 10.411
  },
  "shortlist": {
    "file": "creator-voice/shortlist.wav",
    "seconds": 13.227
  },
  "negotiate": {
    "file": "creator-voice/negotiate.wav",
    "seconds": 12.885
  },
  "contract": {
    "file": "creator-voice/contract.wav",
    "seconds": 14.336
  },
  "secured": {
    "file": "creator-voice/secured.wav",
    "seconds": 15.36
  },
  "deliver": {
    "file": "creator-voice/deliver.wav",
    "seconds": 10.069
  },
  "paid": {
    "file": "creator-voice/paid.wav",
    "seconds": 18.603
  },
  "outro": {
    "file": "creator-voice/outro.wav",
    "seconds": 12.885
  }
};
