// Generated by scripts/gen-campaign-voice.ts — do not edit by hand.
export const LIFECYCLE_VOICE: Record<string, { file: string; seconds: number }> = {
  "hook": {
    "file": "lifecycle-voice/hook.wav",
    "seconds": 9.899
  },
  "create": {
    "file": "lifecycle-voice/create.wav",
    "seconds": 12.971
  },
  "bids": {
    "file": "lifecycle-voice/bids.wav",
    "seconds": 12.373
  },
  "accept": {
    "file": "lifecycle-voice/accept.wav",
    "seconds": 9.472
  },
  "contract": {
    "file": "lifecycle-voice/contract.wav",
    "seconds": 11.691
  },
  "securefunds": {
    "file": "lifecycle-voice/securefunds.wav",
    "seconds": 12.288
  },
  "deliver": {
    "file": "lifecycle-voice/deliver.wav",
    "seconds": 9.045
  },
  "approve": {
    "file": "lifecycle-voice/approve.wav",
    "seconds": 11.264
  },
  "analytics": {
    "file": "lifecycle-voice/analytics.wav",
    "seconds": 19.285
  },
  "outro": {
    "file": "lifecycle-voice/outro.wav",
    "seconds": 14.848
  }
};
