// Generated by scripts/gen-campaign-voice.ts — do not edit by hand.
export const CAMPAIGN_VOICE: Record<string, { file: string; seconds: number }> = {
  "hook": {
    "file": "campaign-voice/hook.wav",
    "seconds": 5.717
  },
  "type": {
    "file": "campaign-voice/type.wav",
    "seconds": 8.875
  },
  "basics-a": {
    "file": "campaign-voice/basics-a.wav",
    "seconds": 8.533
  },
  "basics-b": {
    "file": "campaign-voice/basics-b.wav",
    "seconds": 10.155
  },
  "content": {
    "file": "campaign-voice/content.wav",
    "seconds": 9.387
  },
  "budget": {
    "file": "campaign-voice/budget.wav",
    "seconds": 8.96
  },
  "requirements": {
    "file": "campaign-voice/requirements.wav",
    "seconds": 9.813
  },
  "review": {
    "file": "campaign-voice/review.wav",
    "seconds": 7.936
  },
  "publish": {
    "file": "campaign-voice/publish.wav",
    "seconds": 6.4
  },
  "outro": {
    "file": "campaign-voice/outro.wav",
    "seconds": 9.216
  }
};
