-- Wave D task D3 follow-up (wiki/decisions/2026-07-07-d3-campaign-gating-scope.md) -- extends the
-- store-connection gate (D3) from the AI-drafted path (CreateCampaignExecutor / campaign_intents,
-- V13) to the human REST creation path (CampaignController -> CampaignService.create). Today
-- `campaigns` has no campaign-type concept at all, so that path cannot express (or therefore gate)
-- a DIRECT/"sale" campaign.
--
-- Reuses the EXISTING CampaignIntentType taxonomy (HYPE/DIRECT/REVIEW/STANDARD -- same ENUM values
-- as V13 campaign_intents.campaign_type) rather than inventing a parallel one, so both creation
-- paths share one shared predicate (IntegrationHealthService) for "does this campaign type require
-- a connected store integration" -- see CampaignService.create and CreateCampaignExecutor.
--
-- NULLABLE, no backfill: every existing row predates this concept entirely (the human form has
-- never sent a type), so there is no correct non-null value to backfill to -- guessing DIRECT would
-- retroactively (and incorrectly) gate pre-existing campaigns against a rule that didn't exist when
-- they were created, and guessing STANDARD would assert a fact (awareness-only, no store needed)
-- the data doesn't support either. NULL is treated as "not gated" (see CampaignService.create /
-- IntegrationHealthService), which is also the correct default for new human-path requests that
-- don't yet send a type (the brand-facing form has not been updated to send one as of this
-- migration -- see the ADR's "interim safety for untyped/legacy requests" note) until Ananya wires
-- the form to send DIRECT for sale/conversion objectives.
--
-- [CTO RULING -- wiki/decisions/2026-07-06-phase2-timescaledb-datastore.md, LOCKED] Same MySQL
-- translation discipline as V13/V27/V29 -- ENUM matches the Java enum's exact value set.
ALTER TABLE campaigns
  ADD COLUMN campaign_type ENUM('HYPE','DIRECT','REVIEW','STANDARD') NULL AFTER status;
