CREATE TABLE campaigns (
  id                    VARCHAR(26) PRIMARY KEY,
  workspace_id          VARCHAR(26) NOT NULL,
  title                 VARCHAR(300) NOT NULL,
  description           TEXT,
  status                ENUM('DRAFT','PENDING_APPROVAL','ACTIVE','PAUSED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  budget_min            DECIMAL(12,2),
  budget_max            DECIMAL(12,2),
  currency              VARCHAR(3) NOT NULL DEFAULT 'INR',
  start_date            DATE,
  end_date              DATE,
  application_deadline  DATE,
  platforms             JSON,
  content_types         JSON,
  objectives            JSON,
  requirements          JSON,
  hashtags              JSON,
  target_audience       JSON,
  brand_guidelines      TEXT,
  is_private            BOOLEAN NOT NULL DEFAULT FALSE,
  max_collaborators     INT,
  created_by            VARCHAR(26) NOT NULL,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_campaign_workspace (workspace_id),
  INDEX idx_campaign_status (status),
  CONSTRAINT fk_campaign_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  CONSTRAINT fk_campaign_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
