#!/usr/bin/env bash
# Gate: the files crawlers and social/AI unfurlers fetch by URL must actually
# exist, and the sitemap must list every page the site really has.
#
# TWO FAILURES THIS EXISTS TO PREVENT
# -----------------------------------
# 1. F-0337 — a referenced static asset that was never created.
#    index.html and src/lib/seo/schema.ts pointed og:image and twitter:image at
#    https://influora.in/og-image.png. The file did not exist. Nothing failed:
#    the build was green, the pages rendered, the tests passed. The only symptom
#    was that every share of the site anywhere — WhatsApp, LinkedIn, Slack, X,
#    and the preview card an AI search surface renders beside a citation —
#    resolved a 404 and degraded to a bare grey link. A missing asset that only
#    a third-party fetcher requests is invisible to every check we had.
#
# 2. F-0339 — a sitemap that could not notice what it was missing.
#    The hand-maintained public/sitemap.xml listed 3 of 6 blog posts. Adding a
#    post never updated it, so half the blog was never submitted for indexing.
#    Same shape as F-0308. The sitemap is now generated by
#    scripts/generate-sitemap.mjs; this gate is what proves the generator is
#    actually reaching everything, rather than trusting that it does.
#
# EXIT: 0 clean · 1 a violation was found · 2 could not run
set -uo pipefail

cd "$(dirname "$0")/../.." || { echo "GATE UNAVAILABLE: cannot reach project root"; exit 2; }

fail=0

# --- 1. referenced static assets exist ------------------------------------
echo "== static assets referenced by URL exist in public/ =="

# Absolute https://influora.in/<file> references in the crawler-facing sources,
# plus root-relative /<file> hrefs in index.html. Directories and route paths
# are excluded: only things with a file extension are assets.
REFS=$(grep -ohE 'https://influora\.in/[A-Za-z0-9._-]+\.[A-Za-z0-9]+|(href|src)="/[A-Za-z0-9._-]+\.[A-Za-z0-9]+"' \
        index.html src/lib/seo/schema.ts 2>/dev/null \
        | sed -E 's#.*https://influora\.in/##; s#.*="/##; s#"$##' \
        | sort -u)

if [ -z "$REFS" ]; then
  echo "GATE UNAVAILABLE: extracted zero asset references — the extraction regex no longer matches."
  exit 2
fi

for asset in $REFS; do
  # /src/main.tsx is the dev entry Vite rewrites at build time, not a public asset.
  case "$asset" in
    main.tsx) continue ;;
  esac
  if [ -f "public/$asset" ]; then
    echo "  ok   public/$asset"
  else
    echo "  FAIL public/$asset is referenced but does not exist"
    echo "         (social + AI unfurlers will 404 on it; nothing else in the build notices)"
    fail=1
  fi
done

# --- 2. the generated sitemap is complete ---------------------------------
echo
echo "== sitemap lists every indexable route and every blog post =="

if [ ! -f dist/sitemap.xml ]; then
  echo "  SKIP dist/sitemap.xml not present — run 'npm run build' first."
  echo "       (this half of the gate is unavailable, not passing)"
  if [ "$fail" -eq 0 ]; then
    echo
    echo "GATE PARTIALLY UNAVAILABLE: assets checked, sitemap not."
    exit 2
  fi
  echo
  echo "FAIL — see above"
  exit 1
fi

command -v node >/dev/null 2>&1 || { echo "GATE UNAVAILABLE: node not on PATH"; exit 2; }

EXPECTED=$(node -e '
import("./scripts/marketing-routes.mjs").then((m) => {
  for (const r of m.INDEXABLE_ROUTES) console.log(r.path);
}).catch((e) => { console.error(e.message); process.exit(3); });
') || { echo "GATE UNAVAILABLE: could not read INDEXABLE_ROUTES"; exit 2; }

for route in $EXPECTED; do
  if grep -qF "<loc>https://influora.in${route}</loc>" dist/sitemap.xml; then
    echo "  ok   $route"
  else
    echo "  FAIL indexable route $route is missing from dist/sitemap.xml"
    fail=1
  fi
done

# Every markdown post must have a <loc>. This is the check the old hand-written
# sitemap structurally could not perform.
posts=0
for f in src/content/blog/*.md; do
  [ -e "$f" ] || continue
  posts=$((posts + 1))
  slug=$(basename "$f" .md)
  if grep -qF "<loc>https://influora.in/blog/${slug}</loc>" dist/sitemap.xml; then
    echo "  ok   /blog/$slug"
  else
    echo "  FAIL blog post $slug exists in src/content/blog/ but is absent from dist/sitemap.xml"
    fail=1
  fi
done
echo "  ($posts post(s) on disk)"

# A noindex page in the sitemap is a contradictory signal Search Console reports
# as an error.
echo
echo "== noindex pages must NOT be in the sitemap =="
for route in /terms /privacy /support /refund-policy /disputes /grievance /kyc /tds /disclosure; do
  if grep -qF "<loc>https://influora.in${route}</loc>" dist/sitemap.xml; then
    echo "  FAIL $route is noindex but is listed in the sitemap"
    fail=1
  fi
done
[ "$fail" -eq 0 ] && echo "  none present"

echo
if [ "$fail" -eq 0 ]; then
  echo "PASS — referenced assets exist; sitemap complete and free of noindex URLs"
  echo "NOT CHECKED: whether the OG image LOOKS right (only that the file exists and is referenced);"
  echo "             whether the deployed host serves public/ at the root;"
  echo "             assets referenced from page bodies rather than index.html / schema.ts."
  exit 0
fi

echo "FAIL — see above"
exit 1
