package com.influora.domain.entity;

import com.influora.domain.enums.MemberInviteStatus;
import com.influora.domain.enums.MemberRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * A pending (or resolved) invitation for {@code email} to join {@code workspaceId} at {@code
 * role}. Task 23 (Phase 3c subscription billing) -- the only write path in the codebase that can
 * ever produce a non-OWNER {@link WorkspaceMember} row; previously {@code AuthService.owner()} at
 * brand signup was the sole creator of any {@code workspace_members} row.
 *
 * <p><b>{@code inviteTokenHash}</b> stores SHA-256({@code rawToken}) (see {@code
 * com.influora.security.JwtService#hashToken}) -- the raw, unguessable token ({@code
 * JwtService#createRefreshTokenValue}) is only ever placed in the invite email, mirroring the
 * existing {@link PasswordResetToken} convention. Never log or persist the raw token.
 */
@Entity
@Table(name = "workspace_member_invites")
public class WorkspaceMemberInvite {

    @Id
    @Column(length = 26)
    private String id;

    @Column(name = "workspace_id", nullable = false, length = 26)
    private String workspaceId;

    @Column(nullable = false, length = 255)
    private String email;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private MemberRole role;

    @Column(name = "invite_token_hash", nullable = false, length = 64)
    private String inviteTokenHash;

    @Column(name = "invited_by_user_id", nullable = false, length = 26)
    private String invitedByUserId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private MemberInviteStatus status;

    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    @Column(name = "accepted_at")
    private Instant acceptedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected WorkspaceMemberInvite() {}

    public String getId() {
        return id;
    }

    public String getWorkspaceId() {
        return workspaceId;
    }

    public String getEmail() {
        return email;
    }

    public MemberRole getRole() {
        return role;
    }

    public String getInviteTokenHash() {
        return inviteTokenHash;
    }

    public String getInvitedByUserId() {
        return invitedByUserId;
    }

    public MemberInviteStatus getStatus() {
        return status;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public Instant getAcceptedAt() {
        return acceptedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public boolean isExpired() {
        return Instant.now().isAfter(expiresAt);
    }

    public void markAccepted() {
        this.status = MemberInviteStatus.ACCEPTED;
        this.acceptedAt = Instant.now();
    }

    public void markExpired() {
        this.status = MemberInviteStatus.EXPIRED;
    }

    public void markRevoked() {
        this.status = MemberInviteStatus.REVOKED;
    }

    /**
     * Re-sends this still-PENDING invite: rotates the token (a fresh raw token is generated by
     * the caller and only its hash lands here -- invalidates whatever link was in the first
     * email, which is the safer default if that email was forwarded/leaked) and pushes {@code
     * expiresAt} out another 7 days from now. Used by {@code WorkspaceMemberService#inviteMember}
     * when a second invite is sent to an email with an existing PENDING row -- see that method's
     * javadoc for the dedup decision.
     */
    public void resend(String newInviteTokenHash, Instant newExpiresAt) {
        this.inviteTokenHash = newInviteTokenHash;
        this.expiresAt = newExpiresAt;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private final WorkspaceMemberInvite i = new WorkspaceMemberInvite();

        public Builder id(String id) {
            i.id = id;
            return this;
        }

        public Builder workspaceId(String workspaceId) {
            i.workspaceId = workspaceId;
            return this;
        }

        public Builder email(String email) {
            i.email = email;
            return this;
        }

        public Builder role(MemberRole role) {
            i.role = role;
            return this;
        }

        public Builder inviteTokenHash(String inviteTokenHash) {
            i.inviteTokenHash = inviteTokenHash;
            return this;
        }

        public Builder invitedByUserId(String invitedByUserId) {
            i.invitedByUserId = invitedByUserId;
            return this;
        }

        public Builder expiresAt(Instant expiresAt) {
            i.expiresAt = expiresAt;
            return this;
        }

        public WorkspaceMemberInvite build() {
            i.status = MemberInviteStatus.PENDING;
            i.createdAt = Instant.now();
            return i;
        }
    }
}
