#!/usr/bin/env python3
"""
build_report.py — Consolidated test-report generator for the `tester` skill.

Reads a findings JSON and writes BOTH a Markdown report and a self-contained
HTML dashboard. Keeps severity weighting, health %, and verdict logic in one
place so every test run reports consistently.

Usage:
    python3 build_report.py --findings findings.json --out wiki/reports/ --task "Turmeric page"

findings.json shape:
{
  "task": "Turmeric product page",
  "date": "2026-07-22",
  "target": "src/app/products/turmeric/, /api/products/turmeric",
  "stages_run": ["Build", "Functional", "Security"],
  "findings": [
    {"tester":"Kavya","type":"Functional","severity":"High",
     "title":"Missing input validation","where":"api/products/route.ts:22",
     "issue":"Body is trusted without a schema check","fix":"Validate with zod before use"}
  ]
}
`date` and `verdict` are optional — computed if absent (date falls back to the
value you pass or is left as provided; verdict is always recomputed from findings).
"""

import argparse
import html
import json
import os

SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
SEV_WEIGHT = {"Critical": 25, "High": 10, "Medium": 4, "Low": 1}
SEV_COLOR = {
    "Critical": "#c0392b",
    "High": "#e67e22",
    "Medium": "#f1c40f",
    "Low": "#3498db",
}
OK_COLOR = "#27ae60"


def norm_sev(s):
    s = (s or "").strip().capitalize()
    return s if s in SEV_ORDER else "Low"


def compute_health(findings):
    score = 100
    for f in findings:
        score -= SEV_WEIGHT.get(norm_sev(f.get("severity")), 1)
    return max(0, round(score))


def compute_verdict(findings):
    sevs = {norm_sev(f.get("severity")) for f in findings}
    types = {(f.get("type") or "").strip() for f in findings}
    if not findings:
        return "PASS ✅"
    if "Critical" in sevs:
        return "FAIL ❌"
    if "High" in sevs:
        if "Security" in types or "Build" in types:
            return "FAIL ❌"
        return "PASS WITH REQUIRED FIXES ⚠️"
    return "PASS ✅"


def counts(findings):
    c = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for f in findings:
        c[norm_sev(f.get("severity"))] += 1
    return c


def sorted_findings(findings):
    return sorted(findings, key=lambda f: SEV_ORDER.get(norm_sev(f.get("severity")), 3))


def render_markdown(data):
    findings = data.get("findings", [])
    c = counts(findings)
    health = compute_health(findings)
    verdict = compute_verdict(findings)
    task = data.get("task", "Untitled")
    lines = []
    lines.append(f"# 🧪 Test Report: {task}\n")
    lines.append(f"- **Date:** {data.get('date', '')}")
    lines.append(f"- **Target:** {data.get('target', '')}")
    lines.append(f"- **Stages run:** {', '.join(data.get('stages_run', []))}")
    lines.append(f"- **Health:** {health}%")
    lines.append(f"- **Verdict:** {verdict}\n")
    lines.append("## Summary\n")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for s in ("Critical", "High", "Medium", "Low"):
        lines.append(f"| {s} | {c[s]} |")
    lines.append("")

    # group by tester
    by_tester = {}
    for f in findings:
        by_tester.setdefault(f.get("tester", "Unknown"), []).append(f)

    lines.append("## Findings by tester\n")
    if not findings:
        lines.append("_No issues found. Clean run._ ✅\n")
    for tester, items in by_tester.items():
        ftype = items[0].get("type", "")
        lines.append(f"### {tester} — {ftype}\n")
        for f in sorted_findings(items):
            sev = norm_sev(f.get("severity"))
            lines.append(f"#### [{sev}] {f.get('title', '')}")
            lines.append(f"- **Where:** {f.get('where', '')}")
            lines.append(f"- **Issue:** {f.get('issue', '')}")
            lines.append(f"- **Fix:** {f.get('fix', '')}\n")

    lines.append("## Next steps")
    lines.append("- Route Critical/High blockers to Ananya (frontend) / Vikram (backend) via Arjun.")
    lines.append("- Escalate Critical to Swapnil via Kavya/Priya.")
    lines.append("- Re-run the same stage after fixes before final PASS.\n")
    lines.append("_Generated by the `tester` skill._")
    return "\n".join(lines)


def render_html(data):
    findings = data.get("findings", [])
    c = counts(findings)
    health = compute_health(findings)
    verdict = compute_verdict(findings)
    task = html.escape(data.get("task", "Untitled"))
    target = html.escape(data.get("target", ""))
    date = html.escape(data.get("date", ""))
    stages = html.escape(", ".join(data.get("stages_run", [])))

    verdict_color = OK_COLOR if verdict.startswith("PASS") and "REQUIRED" not in verdict \
        else (SEV_COLOR["High"] if "REQUIRED" in verdict else SEV_COLOR["Critical"])
    health_color = OK_COLOR if health >= 85 else (SEV_COLOR["High"] if health >= 60 else SEV_COLOR["Critical"])

    tiles = ""
    for s in ("Critical", "High", "Medium", "Low"):
        tiles += (
            f'<div class="tile" style="border-top:4px solid {SEV_COLOR[s]}">'
            f'<div class="tnum">{c[s]}</div><div class="tlabel">{s}</div></div>'
        )

    by_tester = {}
    for f in findings:
        by_tester.setdefault(f.get("tester", "Unknown"), []).append(f)

    sections = ""
    if not findings:
        sections = f'<p class="clean">No issues found — clean run. ✅</p>'
    for tester, items in by_tester.items():
        ftype = html.escape(items[0].get("type", ""))
        rows = ""
        for f in sorted_findings(items):
            sev = norm_sev(f.get("severity"))
            rows += (
                f'<div class="finding" style="border-left:5px solid {SEV_COLOR[sev]}">'
                f'<span class="badge" style="background:{SEV_COLOR[sev]}">{sev}</span>'
                f'<span class="ftitle">{html.escape(f.get("title", ""))}</span>'
                f'<div class="fmeta"><b>Where:</b> {html.escape(f.get("where", ""))}</div>'
                f'<div class="fmeta"><b>Issue:</b> {html.escape(f.get("issue", ""))}</div>'
                f'<div class="fmeta"><b>Fix:</b> {html.escape(f.get("fix", ""))}</div>'
                f'</div>'
            )
        sections += (
            f'<details open><summary>{html.escape(tester)} — {ftype} '
            f'({len(items)} finding{"s" if len(items) != 1 else ""})</summary>{rows}</details>'
        )

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Test Report — {task}</title>
<style>
  :root {{ color-scheme: light dark; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    margin: 0; background: #f4f5f7; color: #1a1a2e; }}
  .wrap {{ max-width: 960px; margin: 0 auto; padding: 24px; }}
  header {{ background: #fff; border-radius: 14px; padding: 24px; display: flex;
    gap: 24px; align-items: center; box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  .ring {{ width: 110px; height: 110px; border-radius: 50%; flex: none;
    display: grid; place-items: center; color: #fff; font-size: 26px; font-weight: 700;
    background: {health_color}; }}
  h1 {{ margin: 0 0 6px; font-size: 22px; }}
  .meta {{ color: #555; font-size: 14px; line-height: 1.6; }}
  .verdict {{ display: inline-block; margin-top: 8px; padding: 6px 14px; border-radius: 20px;
    color: #fff; font-weight: 700; background: {verdict_color}; }}
  .tiles {{ display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; margin: 20px 0; }}
  .tile {{ background: #fff; border-radius: 12px; padding: 16px; text-align: center;
    box-shadow: 0 1px 4px rgba(0,0,0,.06); }}
  .tnum {{ font-size: 30px; font-weight: 700; }}
  .tlabel {{ color: #666; font-size: 13px; text-transform: uppercase; letter-spacing: .5px; }}
  details {{ background: #fff; border-radius: 12px; margin-bottom: 12px; padding: 6px 16px;
    box-shadow: 0 1px 4px rgba(0,0,0,.06); }}
  summary {{ font-weight: 600; font-size: 16px; padding: 10px 0; cursor: pointer; }}
  .finding {{ background: #fafafa; border-radius: 8px; padding: 12px 14px; margin: 10px 0; }}
  .badge {{ color: #fff; font-size: 11px; font-weight: 700; padding: 2px 8px;
    border-radius: 10px; margin-right: 8px; text-transform: uppercase; }}
  .ftitle {{ font-weight: 600; }}
  .fmeta {{ font-size: 14px; color: #333; margin-top: 6px; }}
  .clean {{ background: #fff; border-radius: 12px; padding: 24px; text-align: center;
    font-size: 18px; color: {OK_COLOR}; font-weight: 600; }}
  footer {{ text-align: center; color: #999; font-size: 12px; margin: 24px 0; }}
</style></head>
<body><div class="wrap">
  <header>
    <div class="ring">{health}%</div>
    <div>
      <h1>🧪 Test Report — {task}</h1>
      <div class="meta"><b>Target:</b> {target}<br>
        <b>Date:</b> {date} &nbsp;·&nbsp; <b>Stages:</b> {stages}</div>
      <div class="verdict">{html.escape(verdict)}</div>
    </div>
  </header>
  <div class="tiles">{tiles}</div>
  {sections}
  <footer>Generated by the <b>tester</b> skill · Sage Digital</footer>
</div></body></html>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--findings", required=True, help="path to findings JSON")
    ap.add_argument("--out", default=".", help="output directory")
    ap.add_argument("--task", default=None, help="override task name")
    args = ap.parse_args()

    with open(args.findings, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    if args.task:
        data["task"] = args.task
    data.setdefault("findings", [])

    os.makedirs(args.out, exist_ok=True)
    slug = "".join(ch if ch.isalnum() else "-" for ch in data.get("task", "report")).strip("-").lower()
    date = data.get("date", "")
    stem = f"test-report-{slug}" + (f"-{date}" if date else "")

    md_path = os.path.join(args.out, stem + ".md")
    html_path = os.path.join(args.out, stem + ".html")
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write(render_markdown(data))
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(render_html(data))

    print(f"Health: {compute_health(data['findings'])}%  Verdict: {compute_verdict(data['findings'])}")
    print(f"Markdown: {md_path}")
    print(f"HTML:     {html_path}")


if __name__ == "__main__":
    main()
