package com.influora.service.risk.rules;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import com.influora.service.risk.RiskText;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * K-2b (Priya, {@code RULINGS-U-0917.md} rounds 4 and 5; Kabir, {@code KABIR-CONSENT-0917.md}
 * "Last call — K-2"). The labelled corpus test that is {@code HIDE_DISCLOSURE} and {@code
 * OFF_PLATFORM_PAYMENT}'s pattern contract, replacing the SPEC.md &sect;5.2 verbatim-regex cells
 * (AMEND-0917, AMEND-0917-R5).
 *
 * <p><b>Sources, tagged in {@link Row#source()}</b> — never mixed, per round 4 &sect;2 item 4's
 * "each row has a source column" and the requirement that Nisha's rows stay separate and unedited:
 *
 * <ul>
 *   <li>{@code nisha_blind} — all 56 rows of {@code NISHA-RISK-CORPUS-0917.md}, written before she
 *       opened any pattern, ruling, or {@code RegexProbe} file. <b>Labels are hers; this file must
 *       never edit one to make it pass.</b> Loaded from {@code
 *       src/test/resources/risk-corpus/nisha-blind-0917.tsv}, generated byte-for-byte from her
 *       markdown by {@code gen_nisha_blind_tsv.py} next to it — NOT hand-embedded. Kavya's K-2b QA
 *       (KAVYA-K2B-0917.md) found 5 of the 56 rows hand-retyped into an earlier version of this
 *       file differed from her markdown by exactly one character each: a candra-O (U+0911) typed
 *       as plain O (U+0913) in HD-F-07, and a decomposed nukta (U+091C + U+093C) typed as
 *       precomposed U+095B in OPP-F-07, OPP-F-08, OPP-F-13 and HD-N-07 — an input she never wrote,
 *       introduced by retyping, and exactly the class of defect a "blind, verbatim" corpus exists
 *       to rule out. {@link #nishaBlindResourceMatchesMarkdownVerbatim()} is the standing guard
 *       against a repeat.
 *   <li>{@code kabir} — phrases quoted verbatim in {@code KABIR-CONSENT-0917.md} "Last call — K-2",
 *       plus the KB5-1 and KB5-2 additions from "Last call — K-2b round 5": the two on-platform
 *       "send"-in-a-different-sentence texts that must NOT flag {@code OFF_PLATFORM_PAYMENT} without
 *       the token-proximity window, "PhonePe number bhejo…" which must still flag with it, and the
 *       six {@code HIDE_DISCLOSURE} rows covering the Hinglish short form, the Devanagari short form
 *       and "don't mention it's sponsored" — branches no row exercised before KB5-2.
 *   <li>{@code round4} — Priya's own additions, {@code RULINGS-U-0917.md} round 4 &sect;2 item 4
 *       ("mine"). Kept as Java literals: not blind, not subject to the fidelity requirement above.
 *   <li>{@code trigger_text} — {@code CreatorBriefServiceRealRiskRulesTest.TRIGGER_TEXT}, which
 *       must keep firing both flags through this change.
 * </ul>
 *
 * <p><b>Round 5, Ruling 1 (OFF_PLATFORM_PAYMENT only).</b> {@code OPP-N-02}, {@code OPP-N-09} and
 * Kabir's own {@code KAB-OP-N-03} were false positives under round 4's bare {@code upi} match — all
 * three on-platform payout instructions. Priya's ruling: a payment method's name is not a signal on
 * its own; it counts only together with a request to send or pay money TO the creator. See {@code
 * OffPlatformPaymentRule.WALLET_NAME} / {@code .SEND_REQUEST} / {@code .ROUTE_PHRASES}'s javadoc.
 * {@link #offPlatformPaymentHasNoFalsePositives()} is now a plain zero-false-positive assertion —
 * the disputed set from round 4 no longer exists.
 *
 * <p><b>What is asserted vs. only reported.</b> Per round 4's "the test reports hits, false flags
 * and misses per rule and per source, so Kavya and Kabir read numbers, not just a green bar":
 * {@link #printFullReport()} always passes and prints every group's TP/FP/TN/FN, precision and
 * recall. Recall is NOT a hard floor here — Kabir's Q1: "the regex cannot be a security control
 * against a motivated brand," recall is a calibration input for the separate, real-brief-sample
 * gate (round 4 item 5c), not this synthetic corpus, and it is measured live before go-live, not in
 * this test. What round 5 Ruling 2b requires instead: precision is a hard floor (zero false
 * positives on every labelled NO_FLAG row, both rules) and recall is a RATCHET — an exact, named
 * set of row ids that must stay caught ({@link #HIDE_DISCLOSURE_STILL_CATCHES}, {@link
 * #OFF_PLATFORM_PAYMENT_STILL_CATCHES}), not a percentage a test could pass by trading one catch
 * for another. Removing an id from either set needs a written reason and Kabir's sign-off.
 */
class RiskFlagCorpusTest {

    private static final String HD = HideDisclosureRule.CODE;
    private static final String OP = OffPlatformPaymentRule.CODE;

    /** CreatorBriefServiceRealRiskRulesTest.TRIGGER_TEXT, verbatim. */
    private static final String TRIGGER_TEXT =
            "Please pay via UPI after posting, and please don't disclose this as a paid"
                    + " partnership — just keep it looking organic.";

    record Row(String id, String rule, String language, String text, boolean expectFlag, String source) {}

    /** The rule's own text path — not a single {@link RiskText#matches} call, because {@code
     * OFF_PLATFORM_PAYMENT} (round 5) ANDs two patterns together. */
    private static boolean matches(String rule, String text) {
        return rule.equals(HD)
                ? RiskText.matches(text, HideDisclosureRule.HIDE_TEXT)
                : OffPlatformPaymentRule.matches(text);
    }

    private static Row row(String id, String rule, String lang, String text, boolean expect, String source) {
        return new Row(id, rule, lang, text, expect, source);
    }

    // ------------------------------------------------------------------
    // Nisha's 56 rows, loaded verbatim from the generated TSV resource (fidelity fix).
    // ------------------------------------------------------------------

    private static final String NISHA_TSV_RESOURCE = "/risk-corpus/nisha-blind-0917.tsv";

    private static final List<Row> NISHA_BLIND_ROWS = loadNishaBlindRows();

    private static List<Row> loadNishaBlindRows() {
        List<Row> rows = new ArrayList<>();
        try (InputStream in = RiskFlagCorpusTest.class.getResourceAsStream(NISHA_TSV_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        "test resource " + NISHA_TSV_RESOURCE + " is missing — run "
                                + "influora-api/src/test/resources/risk-corpus/gen_nisha_blind_tsv.py");
            }
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) {
                    continue;
                }
                String[] cells = line.split("\t", -1);
                if (cells.length != 6) {
                    throw new IllegalStateException("malformed TSV row (expected 6 columns): " + line);
                }
                rows.add(new Row(cells[0], cells[1], cells[2], cells[3], "FLAG".equals(cells[4]), cells[5]));
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        if (rows.size() != 56) {
            throw new IllegalStateException("expected 56 Nisha rows, loaded " + rows.size());
        }
        return List.copyOf(rows);
    }

    // ------------------------------------------------------------------
    // Round 7 / K-2c.2 (R7-A, F-0778, HIGH): Nisha's 14 blind ASCI-compliance rows (NC-01..NC-14),
    // loaded the same mechanical way as the 56 rows above -- via a generated TSV, never retyped as
    // Java literals -- so the same class of byte-level fidelity defect gen_nisha_blind_tsv.py exists
    // to prevent cannot creep in here either. All 14 are NO_FLAG (RULINGS-U-0917.md round 7, "New,
    // R7-A", required: "At least 12 rows: 4 English, 4 Hinglish, 4 Hindi... 0 may flag").
    // ------------------------------------------------------------------

    private static final String NISHA_COMPLIANCE_TSV_RESOURCE = "/risk-corpus/nisha-compliance-r7.tsv";

    private static final List<Row> NISHA_COMPLIANCE_ROWS = loadNishaComplianceRows();

    private static List<Row> loadNishaComplianceRows() {
        List<Row> rows = new ArrayList<>();
        try (InputStream in = RiskFlagCorpusTest.class.getResourceAsStream(NISHA_COMPLIANCE_TSV_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        "test resource " + NISHA_COMPLIANCE_TSV_RESOURCE + " is missing — run "
                                + "influora-api/src/test/resources/risk-corpus/gen_nisha_compliance_tsv.py");
            }
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) {
                    continue;
                }
                String[] cells = line.split("\t", -1);
                if (cells.length != 6) {
                    throw new IllegalStateException("malformed TSV row (expected 6 columns): " + line);
                }
                rows.add(new Row(cells[0], cells[1], cells[2], cells[3], "FLAG".equals(cells[4]), cells[5]));
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        if (rows.size() != 14) {
            throw new IllegalStateException("expected 14 Nisha compliance rows, loaded " + rows.size());
        }
        if (rows.stream().anyMatch(Row::expectFlag)) {
            throw new IllegalStateException("NISHA-COMPLIANCE-ROWS-0918.md's rows are all documented NO_FLAG");
        }
        return List.copyOf(rows);
    }

    // ------------------------------------------------------------------
    // Non-blind rows: Kabir's probes, Priya's round-4 "mine" additions, TRIGGER_TEXT.
    // Kept as Java literals -- not blind, not subject to the fidelity requirement.
    // ------------------------------------------------------------------

    private static final List<Row> NON_BLIND_ROWS = buildNonBlindRows();

    private static List<Row> buildNonBlindRows() {
        List<Row> rows = new ArrayList<>();

        // ---- Kabir, OFF_PLATFORM_PAYMENT, real-Java-21 measured false flags (should NOT flag) ----
        rows.add(row("KAB-OP-N-01", OP, "en", "Payment after delivery of the reel", false, "kabir"));
        rows.add(row("KAB-OP-N-02", OP, "en", "Payment after the content goes live, through Influora Secure Payments", false, "kabir"));
        rows.add(row("KAB-OP-N-03", OP, "en", "Add your UPI ID in your Influora profile", false, "kabir"));
        // ---- Kabir, OFF_PLATFORM_PAYMENT, measured misses (should flag) ----
        rows.add(row("KAB-OP-F-01", OP, "en", "pay you directly via Google Pay", true, "kabir"));
        rows.add(row("KAB-OP-F-02", OP, "en", "cash on shoot day", true, "kabir"));

        // ---- Kabir, KB5-1 ("Last call — K-2b round 5"): the un-windowed check paired a wallet
        // name anywhere with a send/pay word anywhere, re-admitting the payout-instruction false
        // positive Ruling 1 removed, through an unrelated "send" in a different sentence. Both are
        // ordinary on-platform briefs and must NOT flag. ----
        rows.add(row("KAB5-N-send-draft", OP, "en",
                "Please send the draft for approval by Friday. Your fee is released to the UPI ID"
                        + " saved in your Influora payout settings.",
                false, "kabir"));
        rows.add(row("KAB5-N-send-files", OP, "en",
                "Send us the raw files on Drive. Make sure your bank account or UPI is added in"
                        + " Influora for withdrawal.",
                false, "kabir"));
        // ---- Kabir, KB5-1: the most common way Indian brands write a real off-platform ask, a
        // wallet name used as the verb with "bhejo" nearby (must stay caught under the window). ----
        rows.add(row("KAB5-F-phonepe-bhejo", OP, "hinglish", "PhonePe number bhejo payment ke liye", true, "kabir"));

        // ---- Priya round 4, "mine": Devanagari nukta, precomposed vs decomposed (both should flag) ----
        rows.add(row("RND-OP-F-nukta-precomposed", OP, "hi",
                "पेमेंट " + "प्लेटफ़ॉर्म" + " के बाहर करेंगे",
                true, "round4"));
        rows.add(row("RND-OP-F-nukta-decomposed", OP, "hi",
                "पेमेंट " + "प्लेट" + "फ" + "़" + "ॉर्म" + " के बाहर करेंगे",
                true, "round4"));

        rows.add(row("TRIGGER_TEXT", OP, "en", TRIGGER_TEXT, true, "trigger_text"));

        // ---- Kabir, HIDE_DISCLOSURE, real-Java-21 measured false flags (should NOT flag) ----
        rows.add(row("KAB-HD-N-01", HD, "en", "Caption: Loving my new TECNO #ad", false, "kabir"));
        rows.add(row("KAB-HD-N-02", HD, "en", "Unboxing the OPPO Reno #collab", false, "kabir"));
        rows.add(row("KAB-HD-N-03", HD, "en", "Try Big Casino #sponsored", false, "kabir"));
        rows.add(row("KAB-HD-N-04", HD, "en", "Please don't disclose the fee to other creators", false, "kabir"));
        rows.add(row("KAB-HD-N-05", HD, "en", "Without disclosing the launch date before 5 March", false, "kabir"));
        rows.add(row("KAB-HD-N-06", HD, "en", "no disclosure issues expected", false, "kabir"));
        // ---- Kabir, HIDE_DISCLOSURE, measured misses (should flag) ----
        rows.add(row("KAB-HD-F-01", HD, "en", "Please don't use #ad on this one", true, "kabir"));
        rows.add(row("KAB-HD-F-02", HD, "en", "Do not add the paid partnership label", true, "kabir"));
        rows.add(row("KAB-HD-F-03", HD, "en", "Please don't" + " " + "#ad this post.", true, "kabir"));
        rows.add(row("KAB-HD-F-04", HD, "en", "no #a" + "​" + "d on this post", true, "kabir"));

        // ---- Kabir, KB5-2 ("Last call — K-2b round 5"): deleting the Hinglish short form left
        // the corpus test green because no row exercised it, nor the Devanagari short form, nor
        // "don't mention it's sponsored". These are Kabir's own probes from "Last call — K-2",
        // tagged "kabir" honestly rather than folded into Nisha's blind set. ----
        rows.add(row("KAB5-HD-F-hinglish-01", HD, "hinglish", "ad mat likhna", true, "kabir"));
        rows.add(row("KAB5-HD-F-hinglish-02", HD, "hinglish", "#ad mat daalna", true, "kabir"));
        rows.add(row("KAB5-HD-F-hinglish-03", HD, "hinglish", "paid partnership mat dikhana", true, "kabir"));
        rows.add(row("KAB5-HD-F-devanagari-01", HD, "hi", "विज्ञापन मत लिखना", true, "kabir"));
        rows.add(row("KAB5-HD-F-devanagari-02", HD, "hi", "#ad मत डालना", true, "kabir"));
        rows.add(row("KAB5-HD-F-dont-mention", HD, "en", "don't mention it's sponsored", true, "kabir"));

        // ---- Priya round 4, "mine" ----
        rows.add(row("RND-HD-N-adventure", HD, "en", "no #adventure hashtags please", false, "round4"));
        rows.add(row("RND-HD-F-nbsp", HD, "en", "we would prefer if you do not" + " " + "#ad this one", true, "round4"));
        rows.add(row("RND-HD-F-zwsp", HD, "en", "no #spon" + "​" + "sored tag please", true, "round4"));

        rows.add(row("TRIGGER_TEXT", HD, "en", TRIGGER_TEXT, true, "trigger_text"));

        // ------------------------------------------------------------------
        // F-0769 / K-2c (RULINGS-U-0917.md round 6, Ruling 1). Rows tagged "round6" unless stated;
        // texts are verbatim from F0769Probe.java `main` (Priya's probe, 2026-09-18).
        // ------------------------------------------------------------------

        // ---- Kabir's XS-1..XS-6 ("Not covered" item 1, KABIR-KB5-CHECK-0918.md): six ordinary
        // on-platform briefs the un-split window still paired across a sentence end. All six, not
        // two: English, Hinglish, Devanagari and the danda (।). Must NOT flag. ----
        rows.add(row("XS-1", OP, "en", "Send the draft by Monday. UPI payouts go through Influora as usual.", false, "kabir"));
        rows.add(row("XS-2", OP, "en", "Please send the reel link. Your UPI ID in Influora gets the fee.", false, "kabir"));
        rows.add(row("XS-3", OP, "hinglish", "Draft bhej do kal tak. UPI se payout Influora pe aayega.", false, "kabir"));
        rows.add(row("XS-4", OP, "hinglish", "Script bhejiye Friday tak. Payment UPI se Influora wallet mein aayega.", false, "kabir"));
        rows.add(row("XS-5", OP, "hi", "ड्राफ्ट भेज दीजिए। भुगतान UPI से Influora पर होगा।", false, "kabir"));
        rows.add(row("XS-6", OP, "en", "Kindly send the invoice through the platform. UPI withdrawal is instant.", false, "kabir"));

        // ---- Kabir's two long-winded real asks (Ruling 3b): known misses, already missed before
        // this change (the wallet name and request word sit further than PAIRING_WINDOW tokens
        // apart within the same sentence). Report-only: NOT in the ratchet, same as KAB-OP-F-02. ----
        rows.add(row("KR-1-longwinded", OP, "en",
                "Can you send across, whenever it suits you today, your UPI details so we can settle this?",
                true, "kabir"));
        rows.add(row("KR-2-longwinded", OP, "en",
                "We will transfer the full amount of Rs 20,000 for the reel to your GPay.",
                true, "kabir"));

        // ---- Priya's 13 real asks with a dot inside them (Rs., a/c no., a decimal, a URL, an
        // e-mail address) — the naive-split trap. Added to the ratchet: all 13 are caught today,
        // and a naive "cut at every '.'" implementation goes red on every one of them. ----
        rows.add(row("AB-rs", OP, "en", "We'll send Rs. 5,000 to your UPI today.", true, "round6"));
        rows.add(row("AB-rs-hinglish", OP, "hinglish", "Hum Rs. 5000 aapke UPI pe bhej denge.", true, "round6"));
        rows.add(row("AB-ru-devanagari", OP, "hi", "हम रु. 5000 आपके UPI पर भेज देंगे।", true, "round6"));
        rows.add(row("AB-inr", OP, "en", "We will pay INR. 8,000 straight to your GPay.", true, "round6"));
        rows.add(row("AB-approx", OP, "en", "We'll pay approx. 5k via PhonePe tonight.", true, "round6"));
        rows.add(row("AB-ac-no", OP, "en", "Send your a/c no. for NEFT please.", true, "round6"));
        rows.add(row("AB-amt", OP, "en", "We'll transfer the amt. on your PhonePe tonight.", true, "round6"));
        rows.add(row("AB-no-digit", OP, "en", "Send UPI No. 98xxxxxx21 so we can pay.", true, "round6"));
        rows.add(row("AB-rupee-sym", OP, "en", "We'll send ₹. 5000 to your GPay.", true, "round6"));
        rows.add(row("AB-decimal", OP, "en", "We'll pay 5.5k on your GPay, skip the app.", true, "round6"));
        rows.add(row("AB-eg", OP, "en", "We can pay you some other way, e.g. GPay or PhonePe.", true, "round6"));
        rows.add(row("SEP-url", OP, "en", "Pay link: send via gpay.app/creator and we'll settle it.", true, "round6"));
        rows.add(row("SEP-email", OP, "en", "Mail the invoice to acct@brand.in and we'll transfer to your UPI.", true, "round6"));

        // ---- Priya's 3 real asks split across two sentences — the price of the fix (Ruling 1
        // "The price"). Report-only: these stop flagging once pairing no longer crosses a sentence
        // end, and that loss is accepted, not ratcheted. ----
        rows.add(row("XR-q", OP, "hinglish", "Kya aap apna UPI de sakte ho? Hum wahan bhej denge.", true, "round6"));
        rows.add(row("XR-dot", OP, "en", "Share your UPI. We'll send it tonight.", true, "round6"));
        rows.add(row("XR-deva", OP, "hi", "अपना UPI नंबर दीजिए। हम वहां भेज देंगे।", true, "round6"));

        // ---- Priya's newline shapes: bullet lists, numbered lists and blank-line paragraphs must
        // NOT pair across the break; two hard-wrapped real asks (a single line break, not a list
        // item or blank line) must still flag and are added to the ratchet. ----
        rows.add(row("NL-bullets", OP, "en",
                "Deliverables:\n- 1 reel\n- Send draft by Monday\nPayment:\n- UPI payout through Influora within 7 days",
                false, "round6"));
        rows.add(row("NL-bullets-num", OP, "en",
                "Timeline:\n1. Send script by Friday\n2. UPI payout via Influora after approval",
                false, "round6"));
        rows.add(row("NL-blank", OP, "en",
                "Please send the draft by Friday\n\nUPI payout goes through Influora",
                false, "round6"));
        rows.add(row("NL-hardwrap-ask", OP, "en",
                "Hi, to keep it simple we can send the fee straight to your\nUPI, faster that way for both of us",
                true, "round6"));
        rows.add(row("NL-hardwrap-ask-2", OP, "hinglish",
                "Aap apna UPI ID\nbhej do, hum wahi pe payment kar denge",
                true, "round6"));
        rows.add(row("NL-crlf-bullets", OP, "en",
                "Scope:\r\n- Send raw files on Drive\r\n- UPI withdrawal from Influora wallet",
                false, "round6"));

        // ------------------------------------------------------------------
        // Round 7 / K-2c.2 (Ruling 4): a "|" typed in place of a danda (no Devanagari keyboard, or
        // a chat-app autocorrect artifact) was not a sentence cut, so an unrelated wallet name and
        // request word either side of it still paired -- measured non-dismissible on three ordinary
        // on-platform briefs, English, Hinglish and Devanagari alike. Adding "|" to
        // SENTENCE_TERMINATOR clears all three; both real asks below, written across a pipe, must
        // still flag (added to the ratchet).
        // ------------------------------------------------------------------
        rows.add(row("PIPE-N-deva", OP, "hi", "ड्राफ्ट भेज दीजिए | भुगतान UPI से Influora पर होगा", false, "round7"));
        rows.add(row("PIPE-N-hinglish", OP, "hinglish", "Draft bhej do kal tak | UPI se payout Influora pe aayega", false, "round7"));
        rows.add(row("PIPE-N-en", OP, "en", "Send the draft by Monday | UPI payouts go through Influora as usual", false, "round7"));
        rows.add(row("PIPE-F-rupee", OP, "en", "We'll send ₹5000 to your UPI | no app needed", true, "round7"));
        rows.add(row("PIPE-F-upi-pay", OP, "en", "Send your UPI | we pay today", true, "round7"));

        // ------------------------------------------------------------------
        // K-2c LOW (c) (Ruling 3c): Nisha's 7 FLAG / 7 NO_FLAG guard rows, one pair per untested
        // HIDE_TEXT alternative (NISHA-HIDE-WORD-ROWS-0918.md). Tagged nisha_guard: non-blind, she
        // read the ruling. The Hinglish #ad alternative is pruned (redundant, measured), not
        // guarded; the Devanagari #ad alternative keeps KAB5-HD-F-devanagari-02 as its guard.
        // ------------------------------------------------------------------
        rows.add(row("NISHA-GUARD-HD-F-sponsored-hinglish", HD, "hinglish",
                "Caption mein 'sponsored' word bilkul mat daalna, dikhna chahiye jaise tumne khud pasand"
                        + " karke post kiya hai.",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-sponsored-hinglish", HD, "hinglish",
                "Is month ke sponsored collabs ka performance report bhej dijiye Monday tak.",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-nahi", HD, "hinglish",
                "Please koi bhi tag ya label nahi lagana jisse pata chale ki yeh paid post hai.",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-nahi", HD, "hinglish",
                "Product abhi tak courier se nahi pahuncha, ek din aur lagega.",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-na", HD, "hinglish",
                "Post ko organic hi rakhna na, #ad ya paid wala kuch bhi mat likhna.",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-na", HD, "hinglish",
                "Shoot kal subah 9 baje start karenge na, location confirm ho gayi hai.",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-laga", HD, "hinglish",
                "Please #ad wala hashtag mat laga, post clean aur organic dikhni chahiye.",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-laga", HD, "hinglish",
                "Reel mein woh trending song laga dena jo pichli baar use kiya tha.",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-mention", HD, "hinglish",
                "Yeh brand ke saath paid arrangement hai, lekin isko kahin bhi caption mein mention mat karna.",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-mention", HD, "hinglish",
                "Reply karte waqt hamara Instagram handle @brandname mention kar dena taaki hum dhundh sakein.",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-sponsored-devanagari", HD, "hi",
                "कैप्शन में कहीं भी 'स्पॉन्सर्ड' मत लिखना, पोस्ट बिल्कुल ऑर्गेनिक लगनी चाहिए।",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-sponsored-devanagari", HD, "hi",
                "इस हफ़्ते के स्पॉन्सर्ड पोस्ट्स की लिस्ट शाम तक भेज दीजिए।",
                false, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-F-nahi-devanagari", HD, "hi",
                "कृपया पोस्ट में यह कहीं भी नहीं दिखाना कि यह एक पेड प्रमोशन है।",
                true, "nisha_guard"));
        rows.add(row("NISHA-GUARD-HD-N-nahi-devanagari", HD, "hi",
                "प्रोडक्ट अभी तक डिलीवर नहीं हुआ है, कृपया थोड़ा इंतज़ार करें।",
                false, "nisha_guard"));

        // ---- vikram, round6: tight, minimal rows for the same 7 alternatives Nisha's guard rows
        // above were meant to cover. Added because none of her 14 rows (measured, printFullReport)
        // trigger the existing short-form patterns -- her natural phrasing either places more words
        // between the trigger and the negator than the branch's plain \s+ allows, uses vocabulary
        // the branch does not recognise, or places the verb before the negator. These 7 rows are
        // mechanical, not naturalistic, and exist only so each alternative has ONE row that
        // genuinely depends on it -- added to the ratchet, and each one is the row named in this
        // change's falsification proof for LOW (c). ----
        rows.add(row("VIK-GUARD-HD-F-sponsored-hinglish", HD, "hinglish", "sponsored mat likhna", true, "round6"));
        rows.add(row("VIK-GUARD-HD-F-nahi", HD, "hinglish", "ad nahi likhna", true, "round6"));
        // VIK-GUARD-HD-F-na ("ad na likhna") pruned in round 7 (Ruling 3; Nisha's yes/no,
        // NISHA-COMPLIANCE-ROWS-0918.md "Short-form check"): brands do not send "na" as a direct
        // negator in front of the disclosure verb this way, so the alternative and its row are both
        // removed together, per round 6 section 3c's test applied to the terse form the pattern
        // actually matches.
        rows.add(row("VIK-GUARD-HD-F-laga", HD, "hinglish", "#ad mat laga", true, "round6"));
        rows.add(row("VIK-GUARD-HD-F-mention", HD, "hinglish", "paid partnership mat mention karna", true, "round6"));
        rows.add(row("VIK-GUARD-HD-F-sponsored-devanagari", HD, "hi", "sponsored मत लिखना", true, "round6"));
        rows.add(row("VIK-GUARD-HD-F-nahi-devanagari", HD, "hi", "#ad नहीं डालना।", true, "round6"));

        // ------------------------------------------------------------------
        // F-0776 (kabir, KABIR-K2C-CHECK-0918.md clause 5): a fresh enumeration of every HIDE_TEXT
        // alternative -- not just the branches F-0766 named -- found 8 of 36 that RiskFlagCorpusTest
        // stayed green without: without, put, #collab, ad\s*tag, sponsored\s+tag, this\s+is (the
        // don't-mention branch), it and ad (the don't-disclose branch). Round 7 (Ruling 1) resolved
        // the 8th, B3's bare `ad`: widened to an?, guarded below by the "an ad" row. The other 7
        // each get one tight, mechanical row below -- the same choice the VIK-GUARD-HD-F-* rows
        // above made for a different 7-alternative gap -- so each row genuinely depends on only the
        // one alternative named in its id, and nothing rescues it through a sibling alternative
        // already in the corpus (e.g. "ad tag" is written with no leading "#", so #ad cannot rescue
        // it if ad\s*tag is deleted).
        // ------------------------------------------------------------------
        // VIK-GUARD2-HD-F-without ("Post it without #ad this time") moved OUT of the ratchet in
        // round 7 / R7-A (F-0778): `without` is pruned from B1's negators entirely because its
        // natural use in a brief is the ASCI-compliance instruction ("post without the paid
        // partnership label"), not a hide ask -- see HideDisclosureRule.HIDE_TEXT's javadoc. The
        // row itself is unchanged and stays in the corpus as a SHOULD_FLAG report-only known miss
        // (same treatment as KAB-OP-F-02), so printFullReport still shows the honest recall cost;
        // it is simply no longer asserted.
        rows.add(row("VIK-GUARD2-HD-F-without", HD, "en", "Post it without #ad this time", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-put", HD, "en", "Don't put #ad on it", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-collab", HD, "en", "No #collab tag please", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-adtag", HD, "en", "No ad tag on this one", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-sponsoredtag", HD, "en", "No sponsored tag please", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-thisis", HD, "en", "Don't mention this is sponsored", true, "f0776"));
        rows.add(row("VIK-GUARD2-HD-F-it", HD, "en", "Don't disclose it as a paid partnership", true, "f0776"));

        // ------------------------------------------------------------------
        // Round 7 (Ruling 1, F-0776): B3's bare `ad` widened to an?. Guard: this row goes red if
        // (?:a\s+)? is restored (no longer admits "an") or if `ad` is deleted from the alternation.
        // ------------------------------------------------------------------
        rows.add(row("VIK-GUARD3-HD-F-an-ad", HD, "en", "Don't disclose this as an ad.", true, "round7"));

        // ------------------------------------------------------------------
        // Round 7, R7-A / F-0778 (HIGH, priya): 13 of 15 lines telling the creator to KEEP, add or
        // place the disclosure label raised the non-dismissible HIDE_DISCLOSURE flag -- a false
        // accusation against the most compliant brands. C1-C12 are Priya's measured trigger lines
        // (RULINGS-U-0917.md round 7, "New, R7-A"); all NO_FLAG, all fed into
        // hideDisclosureHasNoFalsePositives via the corpus's zero-false-positive assertion.
        // ------------------------------------------------------------------
        rows.add(row("C1", HD, "en", "Please do not post without the paid partnership label.", false, "round7"));
        rows.add(row("C2", HD, "en", "No post should go live without #ad.", false, "round7"));
        rows.add(row("C3", HD, "en", "Posts without the #ad tag will not be approved.", false, "round7"));
        rows.add(row("C4", HD, "en", "Never publish without the paid partnership tag, ASCI is strict about this.", false, "round7"));
        rows.add(row("C5", HD, "en", "Content with no #ad label will be rejected.", false, "round7"));
        rows.add(row("C6", HD, "en", "Don't put #ad at the end of the caption, it has to be in the first line.", false, "round7"));
        rows.add(row("C7", HD, "en", "Don't add #ad only in the comments, it must be in the caption.", false, "round7"));
        rows.add(row("C8", HD, "en", "Don't use #ad in the comments; use the paid partnership label in the caption.", false, "round7"));
        rows.add(row("C9", HD, "en", "Do not use the ad tag in place of the paid partnership label.", false, "round7"));
        rows.add(row("C10", HD, "hinglish", "Ad nahi likha toh post approve nahi hoga.", false, "round7"));
        rows.add(row("C11", HD, "hi", "#ad नहीं लगाया तो पोस्ट अप्रूव नहीं होगी।", false, "round7"));
        rows.add(row("C12", HD, "hinglish", "Sponsored nahi likha toh ASCI notice aa sakta hai.", false, "round7"));

        return List.copyOf(rows);
    }

    private static final List<Row> CORPUS = combine();

    private static List<Row> combine() {
        List<Row> all = new ArrayList<>(NISHA_BLIND_ROWS);
        all.addAll(NISHA_COMPLIANCE_ROWS);
        all.addAll(NON_BLIND_ROWS);
        return List.copyOf(all);
    }

    private static Row byId(String rule, String id) {
        return CORPUS.stream()
                .filter(r -> r.rule().equals(rule) && r.id().equals(id))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("no corpus row " + id + " for " + rule));
    }

    // ------------------------------------------------------------------
    // Reporting (always green; the numbers are the K-2b report, not a pass/fail signal)
    // ------------------------------------------------------------------

    @Test
    @DisplayName("K-2b report: TP/FP/TN/FN, precision and recall per rule, ALL vs. nisha_blind vs. everyone else")
    void printFullReport() {
        System.out.println("==== K-2b corpus report (round 5, verbatim Nisha rows) ====");
        for (String rule : List.of(HD, OP)) {
            System.out.println("-- " + rule + " --");
            printGroup(rule, "ALL", r -> true);
            printGroup(rule, "nisha_blind only", r -> r.source().equals("nisha_blind"));
            printGroup(rule, "non-blind (kabir/round4/trigger_text)", r -> !r.source().equals("nisha_blind"));
        }
    }

    private static void printGroup(String rule, String label, Predicate<Row> filter) {
        int tp = 0, fp = 0, tn = 0, fn = 0;
        List<String> fpIds = new ArrayList<>();
        List<String> fnIds = new ArrayList<>();
        for (Row r : CORPUS) {
            if (!r.rule().equals(rule) || !filter.test(r)) continue;
            boolean got = matches(r.rule(), r.text());
            if (r.expectFlag() && got) tp++;
            else if (!r.expectFlag() && got) { fp++; fpIds.add(r.id()); }
            else if (!r.expectFlag()) tn++;
            else { fn++; fnIds.add(r.id()); }
        }
        int total = tp + fp + tn + fn;
        if (total == 0) return;
        double precision = (tp + fp) == 0 ? Double.NaN : (double) tp / (tp + fp);
        double recall = (tp + fn) == 0 ? Double.NaN : (double) tp / (tp + fn);
        System.out.printf(
                "  [%s] n=%d TP=%d FP=%d TN=%d FN=%d precision=%.3f recall=%.3f%n",
                label, total, tp, fp, tn, fn, precision, recall);
        if (!fpIds.isEmpty()) System.out.println("    FP ids: " + fpIds);
        if (!fnIds.isEmpty()) System.out.println("    FN ids: " + fnIds);
    }

    // ------------------------------------------------------------------
    // Fidelity (round 5, item 3): the TSV resource must be byte-identical to Nisha's markdown.
    // ------------------------------------------------------------------

    private static final Pattern FLAG_HEADING = Pattern.compile("^##\\s*Flag\\s*\\d+:\\s*(\\S+)");
    private static final Pattern LABEL_HEADING = Pattern.compile("^###\\s*SHOULD\\s*(NOT\\s*)?FLAG");
    private static final Pattern ROW_ID = Pattern.compile("^[A-Z]+-[A-Z]-\\d+$");

    /** Mirrors gen_nisha_blind_tsv.py's `parse()` exactly, so both must agree or this test finds it. */
    private static List<Row> parseNishaMarkdown(String mdText) {
        List<Row> rows = new ArrayList<>();
        String rule = null;
        Boolean expectFlag = null;
        for (String rawLine : mdText.split("\n", -1)) {
            String line = rawLine.strip();
            Matcher fm = FLAG_HEADING.matcher(line);
            if (fm.find()) {
                rule = fm.group(1);
                continue;
            }
            Matcher lm = LABEL_HEADING.matcher(line);
            if (lm.find()) {
                expectFlag = lm.group(1) == null;
                continue;
            }
            if (!line.startsWith("|")) {
                continue;
            }
            String trimmed = line;
            if (trimmed.startsWith("|")) trimmed = trimmed.substring(1);
            if (trimmed.endsWith("|")) trimmed = trimmed.substring(0, trimmed.length() - 1);
            String[] cells = trimmed.split("\\|", -1);
            if (cells.length < 6) {
                continue;
            }
            for (int i = 0; i < cells.length; i++) {
                cells[i] = cells[i].strip();
            }
            String rowId = cells[0];
            if (!ROW_ID.matcher(rowId).matches()) {
                continue;
            }
            if (rule == null || expectFlag == null) {
                throw new IllegalStateException("row " + rowId + " appears before a Flag/SHOULD-FLAG heading");
            }
            String language = cells[1];
            String text = cells[2];
            if (text.length() >= 2 && text.startsWith("\"") && text.endsWith("\"")) {
                text = text.substring(1, text.length() - 1);
            }
            rows.add(new Row(rowId, rule, language, text, expectFlag, "nisha_blind"));
        }
        return rows;
    }

    private static Path nishaMarkdownPath() {
        // Maven runs tests with the module base directory (influora-api/) as the working directory.
        return Path.of("..", ".proof-os", "tasks", "T-MEERA-CREATOR-PHASE-B", "NISHA-RISK-CORPUS-0917.md");
    }

    @Test
    @DisplayName("fidelity: the TSV resource matches NISHA-RISK-CORPUS-0917.md byte-for-byte, per row")
    void nishaBlindResourceMatchesMarkdownVerbatim() throws IOException {
        Path md = nishaMarkdownPath();
        assumeTrue(Files.exists(md),
                "NISHA-RISK-CORPUS-0917.md not present in this checkout (e.g. CI without .proof-os) "
                        + "-- fidelity not verified here; the resource is trusted as generated");
        String mdText = Files.readString(md, StandardCharsets.UTF_8);
        List<Row> parsed = parseNishaMarkdown(mdText);
        assertThat(parsed)
                .as("TSV resource must match a fresh parse of the markdown, row for row, byte for byte")
                .containsExactlyInAnyOrderElementsOf(NISHA_BLIND_ROWS);
    }

    private static final Pattern COMPLIANCE_ROW_ID = Pattern.compile("^NC-\\d+$");

    /**
     * Mirrors gen_nisha_compliance_tsv.py's `parse()` exactly, so both must agree or this test
     * finds it. NISHA-COMPLIANCE-ROWS-0918.md's first table has no Flag/SHOULD-FLAG headings --
     * every row is HIDE_DISCLOSURE, every row is NO_FLAG -- and is a different shape from
     * NISHA-RISK-CORPUS-0917.md's, so it gets its own parser rather than reusing
     * {@link #parseNishaMarkdown}.
     */
    private static List<Row> parseNishaComplianceMarkdown(String mdText) {
        List<Row> rows = new ArrayList<>();
        for (String rawLine : mdText.split("\n", -1)) {
            String line = rawLine.strip();
            if (!line.startsWith("|")) {
                continue;
            }
            String trimmed = line;
            if (trimmed.startsWith("|")) trimmed = trimmed.substring(1);
            if (trimmed.endsWith("|")) trimmed = trimmed.substring(0, trimmed.length() - 1);
            String[] cells = trimmed.split("\\|", -1);
            if (cells.length < 4) {
                continue;
            }
            for (int i = 0; i < cells.length; i++) {
                cells[i] = cells[i].strip();
            }
            String rowId = cells[0];
            if (!COMPLIANCE_ROW_ID.matcher(rowId).matches()) {
                continue;
            }
            String language = cells[1];
            String text = cells[2];
            if (text.length() >= 2 && text.startsWith("\"") && text.endsWith("\"")) {
                text = text.substring(1, text.length() - 1);
            }
            String expected = cells[3];
            rows.add(new Row(rowId, HD, language, text, "FLAG".equals(expected), "nisha_blind_r7"));
        }
        return rows;
    }

    private static Path nishaComplianceMarkdownPath() {
        // Maven runs tests with the module base directory (influora-api/) as the working directory.
        return Path.of("..", ".proof-os", "tasks", "T-MEERA-CREATOR-PHASE-B", "NISHA-COMPLIANCE-ROWS-0918.md");
    }

    @Test
    @DisplayName("fidelity: the compliance-row TSV resource matches NISHA-COMPLIANCE-ROWS-0918.md byte-for-byte, per row")
    void nishaComplianceResourceMatchesMarkdownVerbatim() throws IOException {
        Path md = nishaComplianceMarkdownPath();
        assumeTrue(Files.exists(md),
                "NISHA-COMPLIANCE-ROWS-0918.md not present in this checkout (e.g. CI without .proof-os) "
                        + "-- fidelity not verified here; the resource is trusted as generated");
        String mdText = Files.readString(md, StandardCharsets.UTF_8);
        List<Row> parsed = parseNishaComplianceMarkdown(mdText);
        assertThat(parsed)
                .as("compliance TSV resource must match a fresh parse of the markdown, row for row, byte for byte")
                .containsExactlyInAnyOrderElementsOf(NISHA_COMPLIANCE_ROWS);
    }

    // ------------------------------------------------------------------
    // Hard, mutation-sensitive assertions
    // ------------------------------------------------------------------

    @Test
    @DisplayName("HIDE_DISCLOSURE: zero false positives across the whole corpus")
    void hideDisclosureHasNoFalsePositives() {
        List<String> falsePositives = CORPUS.stream()
                .filter(r -> r.rule().equals(HD) && !r.expectFlag() && matches(HD, r.text()))
                .map(Row::id)
                .toList();
        assertThat(falsePositives).as("HIDE_DISCLOSURE false positives (must be none)").isEmpty();
    }

    @Test
    @DisplayName("OFF_PLATFORM_PAYMENT: zero false positives across the whole corpus (round 5, Ruling 1)")
    void offPlatformPaymentHasNoFalsePositives() {
        List<String> falsePositives = CORPUS.stream()
                .filter(r -> r.rule().equals(OP) && !r.expectFlag() && matches(OP, r.text()))
                .map(Row::id)
                .toList();
        assertThat(falsePositives)
                .as("OFF_PLATFORM_PAYMENT false positives (must be none -- round 4's disputed bare-UPI"
                        + " trio is resolved by Ruling 1's send/pay-request requirement, not excused)")
                .isEmpty();
    }

    @Test
    @DisplayName("a bare wallet-method name alone, with no send/pay request nearby, stays silent (Ruling 1)")
    void bareWalletNameAloneStaysSilent() {
        List<String> fired = new ArrayList<>();
        for (String name : List.of("upi", "gpay", "phonepe", "paytm", "google pay", "neft", "imps", "rtgs", "bank transfer")) {
            String text = "Just mentioning " + name + " here for reference, nothing else.";
            if (matches(OP, text)) {
                fired.add(name);
            }
        }
        assertThat(fired).as("bare wallet names that must stay silent but fired").isEmpty();
    }

    /**
     * K-2c / Ruling 1: the suppression wraps. The first is the original round-5 wrap (an
     * Influora-safe prefix and suffix); the other three are the probe's additions (round 6), each
     * exercising a different way appended text could accidentally introduce a sentence boundary
     * that un-pairs a caught row: terminators and abbreviations packed around it, a blank-line
     * paragraph on each side, and a Devanagari sentence on each side.
     */
    private static String[] suppressionWraps(String text) {
        return new String[] {
            "Influora wallet note: " + text + " — or through Influora payouts if you prefer",
            "Payouts go via Influora. Rs. 5,000 is the fee. " + text + " No. 12 approx. 3 days. Thanks!",
            "Send the draft by Monday.\n\n" + text + "\n\nUPI payouts go through Influora as usual.",
            "भुगतान Influora से। " + text + " धन्यवाद।",
        };
    }

    @Test
    @DisplayName("suppression: wrapping a caught OFF_PLATFORM_PAYMENT row in Influora-safe or sentence-boundary text must not un-flag it")
    void offPlatformPaymentSuppressionAttemptStillFires() {
        List<String> notSuppressed = new ArrayList<>();
        for (String id : OFF_PLATFORM_PAYMENT_STILL_CATCHES) {
            Row caught = byId(OP, id);
            String[] wraps = suppressionWraps(caught.text());
            for (int i = 0; i < wraps.length; i++) {
                if (!matches(OP, wraps[i])) {
                    notSuppressed.add(id + "#" + (i + 1));
                }
            }
        }
        assertThat(notSuppressed).as("suppression attempts that wrongly un-flagged a ratchet row").isEmpty();
    }

    /**
     * Round 5 Ruling 2b ratchet: the exact set of row ids {@code HIDE_DISCLOSURE} catches today.
     * Adding a catch means adding its id here in the same change. Removing an id needs a written
     * reason in the commit and Kabir's sign-off, because it gives up a literal catch.
     *
     * <p><b>K-2c (round 6, Ruling 3c) finding, NOT yet closed.</b> Nisha's 7 {@code nisha_guard}
     * FLAG rows (below, in {@link #buildNonBlindRows}) were meant to guard the 7 previously-
     * untested {@code HIDE_TEXT} alternatives (Hinglish {@code sponsored}, {@code nahi}, {@code
     * na}, {@code laga}, {@code mention}; Devanagari {@code sponsored}, {@code नहीं}). Measured
     * against the built pattern (this test's own {@code printFullReport}), none of the 7 currently
     * fire: her natural sentences either place more words between the trigger and the negator than
     * the short-form branch's plain {@code \s+} allows, use different vocabulary than the branch's
     * literal alternatives (e.g. "tag"/"label"/"paid post" where the pattern needs {@code ad},
     * {@code sponsored} or {@code paid partnership}; "स्पॉन्सर्ड" where the Devanagari branch has
     * "sponsored" written in Latin script), or place the verb before the negator instead of after
     * it. None are added to this ratchet — an id here must already be caught, or the ratchet
     * becomes exactly the vacuous gate K-2c's own LOW (d) exists to prevent. They stay in the
     * corpus as {@code SHOULD_FLAG} rows, reported by {@link #printFullReport} as known misses
     * (the same treatment as {@code KAB-OP-F-02}), pending Nisha rewriting tighter sentences or a
     * Priya ruling to widen the pattern — out of scope for this change, which round 6 authorised
     * only for the sentence-boundary fix and the {@code #ad} prune.
     *
     * <p>The 7 {@code VIK-GUARD-HD-F-*} rows (also in {@link #buildNonBlindRows}) are added
     * instead: tight, mechanical sentences that genuinely depend on each of the same 7
     * alternatives, so the ratchet has a real (not vacuous) guard for each one.
     *
     * <p><b>F-0776 (kabir, {@code KABIR-K2C-CHECK-0918.md} clause 5).</b> A fresh, exhaustive pass
     * over every {@code HIDE_TEXT} alternative -- not sampled by branch, as the K-2c check that
     * closed the gap above was -- found 8 more with no dependent row: {@code without}, {@code put},
     * {@code #collab}, {@code ad\s*tag}, {@code sponsored\s+tag}, {@code this\s+is} (the
     * don't-mention branch), {@code it} and {@code ad} (the don't-disclose branch). The
     * {@code VIK-GUARD2-HD-F-*} rows guard 6 of the 8 in this ratchet; B3's {@code ad} is guarded by
     * {@code VIK-GUARD3-HD-F-an-ad} below (round 7, Ruling 1 widened it to {@code an?}).
     *
     * <p><b>Round 7 / K-2c.2 (R7-A, F-0778, HIGH).</b> {@code without} is pruned from
     * {@code HIDE_TEXT} entirely (its natural use in a brief is the ASCI-compliance instruction,
     * not a hide ask), so {@code VIK-GUARD2-HD-F-without} leaves this ratchet and stays only as a
     * {@code printFullReport} known miss. {@code VIK-GUARD-HD-F-na} is deleted outright (round 7,
     * Ruling 3; Nisha's yes/no pruned the {@code na} alternative itself, not just its row).
     */
    private static final List<String> HIDE_DISCLOSURE_STILL_CATCHES = List.of(
            "HD-F-02", "HD-F-10",
            "KAB-HD-F-01", "KAB-HD-F-02", "KAB-HD-F-03", "KAB-HD-F-04",
            "RND-HD-F-nbsp", "RND-HD-F-zwsp",
            "KAB5-HD-F-hinglish-01", "KAB5-HD-F-hinglish-02", "KAB5-HD-F-hinglish-03",
            "KAB5-HD-F-devanagari-01", "KAB5-HD-F-devanagari-02", "KAB5-HD-F-dont-mention",
            "VIK-GUARD-HD-F-sponsored-hinglish", "VIK-GUARD-HD-F-nahi",
            "VIK-GUARD-HD-F-laga", "VIK-GUARD-HD-F-mention",
            "VIK-GUARD-HD-F-sponsored-devanagari", "VIK-GUARD-HD-F-nahi-devanagari",
            "VIK-GUARD2-HD-F-put", "VIK-GUARD2-HD-F-collab",
            "VIK-GUARD2-HD-F-adtag", "VIK-GUARD2-HD-F-sponsoredtag", "VIK-GUARD2-HD-F-thisis",
            "VIK-GUARD2-HD-F-it",
            "VIK-GUARD3-HD-F-an-ad",
            "TRIGGER_TEXT");

    /**
     * Same ratchet, for {@code OFF_PLATFORM_PAYMENT}. K-2c (round 6, Ruling 1): the 13 dot-inside
     * asks and the 2 hard-wrapped asks added — all 15 are caught today, and a naive sentence-cut
     * implementation (cutting at every {@code .} or every line break) goes red on them.
     *
     * <p>Round 7 / K-2c.2 (Ruling 4): {@code PIPE-F-rupee} and {@code PIPE-F-upi-pay} added — both
     * real asks written across a {@code |} typed in place of a danda, which must still flag once the
     * pipe is added to {@code SENTENCE_TERMINATOR}.
     */
    private static final List<String> OFF_PLATFORM_PAYMENT_STILL_CATCHES = List.of(
            "OPP-F-01", "OPP-F-04", "OPP-F-07", "OPP-F-11",
            "KAB-OP-F-01", "KAB5-F-phonepe-bhejo",
            "RND-OP-F-nukta-precomposed", "RND-OP-F-nukta-decomposed",
            "AB-rs", "AB-rs-hinglish", "AB-ru-devanagari", "AB-inr", "AB-approx", "AB-ac-no",
            "AB-amt", "AB-no-digit", "AB-rupee-sym", "AB-decimal", "AB-eg", "SEP-url", "SEP-email",
            "NL-hardwrap-ask", "NL-hardwrap-ask-2",
            "PIPE-F-rupee", "PIPE-F-upi-pay",
            "TRIGGER_TEXT");

    @Test
    @DisplayName("ratchet: every row HIDE_DISCLOSURE catches today must stay caught")
    void hideDisclosureStillCatches() {
        List<String> misses = HIDE_DISCLOSURE_STILL_CATCHES.stream()
                .filter(id -> !matches(HD, byId(HD, id).text()))
                .toList();
        assertThat(misses).as("HIDE_DISCLOSURE ratchet rows that stopped catching").isEmpty();
    }

    @Test
    @DisplayName("ratchet: every row OFF_PLATFORM_PAYMENT catches today must stay caught")
    void offPlatformPaymentStillCatches() {
        List<String> misses = OFF_PLATFORM_PAYMENT_STILL_CATCHES.stream()
                .filter(id -> !matches(OP, byId(OP, id).text()))
                .toList();
        assertThat(misses).as("OFF_PLATFORM_PAYMENT ratchet rows that stopped catching").isEmpty();
    }

    @Test
    @DisplayName("TRIGGER_TEXT still fires both flags (CreatorBriefServiceRealRiskRulesTest's fixture)")
    void triggerTextFiresBothFlags() {
        assertThat(matches(HD, TRIGGER_TEXT)).as("HIDE_DISCLOSURE on TRIGGER_TEXT").isTrue();
        assertThat(matches(OP, TRIGGER_TEXT)).as("OFF_PLATFORM_PAYMENT on TRIGGER_TEXT").isTrue();
    }

    /**
     * K-2c / LOW (a) (Ruling 3a): {@link OffPlatformPaymentRule#PAIRING_WINDOW} pinned to exactly 6
     * tokens, with neutral filler and no real wallet/request vocabulary in the gap, so the test is
     * about the window, not about corpus wording. The distances below are the LITERALS 6 and 7, not
     * {@code PAIRING_WINDOW} or {@code PAIRING_WINDOW + 1} — writing them as the constant would pass
     * whatever the constant says and pin nothing.
     */
    @Test
    @DisplayName("K-2c / LOW (a): the pairing window is exactly 6 tokens, in both directions and for a two-word wallet name")
    void pairingWindowIsExactlySix() {
        String[] filler = {"alpha", "bravo", "charlie", "delta", "echo", "foxtrot"};
        String gapSix = String.join(" ", filler[0], filler[1], filler[2], filler[3], filler[4]); // 5 words -> distance 6
        String gapSeven = String.join(" ", filler); // 6 words -> distance 7

        List<String> failures = new ArrayList<>();
        if (!matches(OP, "upi " + gapSix + " send")) failures.add("wallet..request at distance 6 must flag");
        if (!matches(OP, "send " + gapSix + " upi")) failures.add("request..wallet at distance 6 must flag");
        if (!matches(OP, "google pay " + gapSix + " send")) failures.add("two-word wallet name at distance 6 must flag");
        if (matches(OP, "upi " + gapSeven + " send")) failures.add("wallet..request at distance 7 must not flag");
        if (matches(OP, "send " + gapSeven + " upi")) failures.add("request..wallet at distance 7 must not flag");
        if (matches(OP, "google pay " + gapSeven + " send")) failures.add("two-word wallet name at distance 7 must not flag");

        assertThat(failures).as("PAIRING_WINDOW must be exactly 6 tokens").isEmpty();
    }

    /**
     * K-2c (round 6, Ruling 1): a dedicated, named check of the sentence-boundary rule itself, on
     * top of the whole-corpus ratchet and zero-false-positive tests those same rows also feed.
     * Kept separate so a reviewer reading red output sees "sentence boundary" failures grouped, not
     * mixed into the full corpus report.
     */
    @Test
    @DisplayName("K-2c: pairing does not cross a sentence end, but a protected dot, an abbreviation or a hard line-wrap does not count as one")
    void sentenceBoundaryStopsPairingAcrossSentences() {
        List<String> failures = new ArrayList<>();
        for (String id : List.of("XS-1", "XS-2", "XS-3", "XS-4", "XS-5", "XS-6")) {
            if (matches(OP, byId(OP, id).text())) {
                failures.add(id + " must not flag: pairing must not cross a sentence end");
            }
        }
        for (String id : List.of(
                "AB-rs", "AB-inr", "AB-rupee-sym", "AB-ac-no", "AB-amt", "AB-eg",
                "NL-hardwrap-ask", "NL-hardwrap-ask-2")) {
            if (!matches(OP, byId(OP, id).text())) {
                failures.add(id + " must still flag: not a real sentence end");
            }
        }
        if (matches(OP, byId(OP, "NL-bullets").text())) {
            failures.add("NL-bullets must not flag: a line break into a list item is a sentence end");
        }
        assertThat(failures).as("K-2c sentence-boundary behaviour").isEmpty();
    }

    @Test
    @DisplayName("leading boundary: a brand name ending in \"no\" does not fire HIDE_DISCLOSURE")
    void leadingBoundaryProtectsBrandNamesEndingInNo() {
        assertThat(matches(HD, "Caption: Loving my new TECNO #ad")).isFalse();
        assertThat(matches(HD, "Unboxing the OPPO Reno #collab")).isFalse();
        assertThat(matches(HD, "Try Big Casino #sponsored")).isFalse();
    }

    @Test
    @DisplayName("trailing boundary: \"no #adventure hashtags please\" does not fire")
    void trailingBoundaryProtectsHashtagPrefixCollisions() {
        assertThat(matches(HD, "no #adventure hashtags please")).isFalse();
    }

    @Test
    @DisplayName("bare 'disclos' is gone: ordinary confidentiality language does not fire")
    void bareDisclosRemoved() {
        assertThat(matches(HD, "Please don't disclose the fee to other creators")).isFalse();
        assertThat(matches(HD, "Without disclosing the launch date before 5 March")).isFalse();
        assertThat(matches(HD, "no disclosure issues expected")).isFalse();
        assertThat(matches(HD, "Please don't disclose the launch date until the 15th, it's still confidential internally.")).isFalse();
    }

    @Test
    @DisplayName("'pay(ment)? after' is gone: payment timing language does not fire OFF_PLATFORM_PAYMENT")
    void paymentAfterRemoved() {
        assertThat(matches(OP, "Payment after delivery of the reel")).isFalse();
        assertThat(matches(OP, "Payment after the content goes live, through Influora Secure Payments")).isFalse();
    }

    @Test
    @DisplayName("Devanagari nukta: precomposed and decomposed forms both fire OFF_PLATFORM_PAYMENT after NFC")
    void devanagariNuktaBothFormsFire() {
        Row precomposed = byId(OP, "RND-OP-F-nukta-precomposed");
        Row decomposed = byId(OP, "RND-OP-F-nukta-decomposed");
        assertThat(matches(OP, precomposed.text())).as("precomposed nukta form").isTrue();
        assertThat(matches(OP, decomposed.text())).as("decomposed nukta form").isTrue();
    }

    @Test
    @DisplayName("U+00A0 (non-breaking space) is mapped to a space, so the NBSP bypass still fires HIDE_DISCLOSURE")
    void nonBreakingSpaceBypassFixed() {
        assertThat(matches(HD, "Please don't" + " " + "#ad this post.")).isTrue();
        assertThat(matches(HD, "we would prefer if you do not" + " " + "#ad this one")).isTrue();
    }

    @Test
    @DisplayName("U+200B (zero-width space) is stripped, so the ZWSP bypass still fires HIDE_DISCLOSURE")
    void zeroWidthSpaceBypassFixed() {
        assertThat(matches(HD, "no #a" + "​" + "d on this post")).isTrue();
        assertThat(matches(HD, "no #spon" + "​" + "sored tag please")).isTrue();
    }
}
