package com.influora.web;

import com.influora.security.AuthPrincipal;
import com.influora.service.admin.AdminCampaignCouponService;
import com.influora.web.dto.tracking.TrackingDtos.CouponListResponse;
import com.influora.web.dto.tracking.TrackingDtos.CouponResponse;
import com.influora.web.dto.tracking.TrackingDtos.CreateCouponRequest;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Admin-scoped coupon issuing for a campaign (T-FESTIVALBOX-0905 phase 11). Mounted at {@code
 * /admin/campaigns/{campaignId}/coupons} (full path {@code
 * /api/v1/admin/campaigns/{campaignId}/coupons} given {@code server.servlet.context-path=/api/v1}).
 *
 * <p><b>This is the admin twin of {@link CampaignTrackingController}'s {@code /coupons} routes, and
 * it exists because that controller is unreachable to an admin.</b> Those are mounted at {@code
 * /campaigns/{campaignId}} and resolve the workspace through {@code
 * BrandContextService#requireBrandWorkspace}, which rejects any principal whose {@code userType} is
 * not {@code BRAND} with a {@code WRONG_USER_TYPE} 403. Admin JWTs are {@code ADMIN} and there is no
 * impersonation anywhere in this codebase, so before this controller existed an admin literally
 * could not issue a sponsor's coupons — which left the entire Festival Box tracking chain inert,
 * since an unregistered code can never attribute a redemption.
 *
 * <p>Deliberately a separate controller rather than relaxing the brand one: {@code
 * requireBrandWorkspace}'s BRAND-only check is doing real work for every other route on that class,
 * and loosening it to admit admins would widen all of them at once to fix one.
 *
 * <p>Returns the SAME {@link CouponResponse}/{@link CouponListResponse} shapes the brand endpoints
 * do, so the two surfaces cannot describe a coupon differently. Note this means these routes return
 * a bare DTO rather than the {@code ApiResponse} envelope the brand twin uses — matching the
 * {@code Admin*Controller} convention that {@code apiRequest()} in {@code
 * src/admin/services/api-contracts.ts} expects.
 *
 * <p>Role gate (SUPER_ADMIN + ADMIN, MFA satisfied) and the audit-log write both live in {@link
 * AdminCampaignCouponService}: this codebase uses no {@code @PreAuthorize}, so a controller carries
 * no authorization of its own.
 */
@RestController
@RequestMapping("/admin/campaigns/{campaignId}/coupons")
public class AdminCampaignCouponController {

    private final AdminCampaignCouponService adminCampaignCouponService;

    public AdminCampaignCouponController(AdminCampaignCouponService adminCampaignCouponService) {
        this.adminCampaignCouponService = adminCampaignCouponService;
    }

    /**
     * POST /admin/campaigns/{campaignId}/coupons — issue a coupon on the sponsor's behalf.
     *
     * <p>Omit {@code creatorProfileId} (null or blank) to issue the campaign's single BRAND-LEVEL
     * code — the page-exclusive one shown on the Festival Box page. Supply it to issue that
     * creator's own code, which is what makes a sale attributable to them and pays their
     * commission. A second brand-level code on one campaign is refused {@code BRAND_CODE_EXISTS}
     * (409).
     *
     * <p>The response's {@code code} is generated by Influora, not supplied by the caller. Whoever
     * uses this must then create that exact code in the sponsor's own store, or it will fail at
     * their checkout.
     */
    @PostMapping
    public CouponResponse issue(
            @AuthenticationPrincipal AuthPrincipal principal,
            HttpServletRequest httpRequest,
            @PathVariable String campaignId,
            @Valid @RequestBody CreateCouponRequest request) {
        return adminCampaignCouponService.issue(
                principal,
                httpRequest,
                campaignId,
                request.creatorProfileId(),
                request.discountType(),
                request.discountValue(),
                request.usageLimit(),
                request.expiresAt());
    }

    /** GET /admin/campaigns/{campaignId}/coupons — every coupon issued on this campaign. */
    @GetMapping
    public CouponListResponse list(
            @AuthenticationPrincipal AuthPrincipal principal, @PathVariable String campaignId) {
        return new CouponListResponse(adminCampaignCouponService.list(principal, campaignId));
    }
}
